/*
 * File: app/view/CensusFreezeCont.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.CensusFreezeCont', {
    extend: 'Ext.Container',
    alias: 'widget.censusFreezeCont',

    requires: [
        'Ext.Container'
    ],

    config: {
        itemId: 'censusFreezeCont',
        layout: 'hbox',
        items: [
            {
                xtype: 'touchtreegrid',
                store: 'censusFreezeStore',
                onItemDisclosure: false,
                columns: [
                    {
                        header: 'Region',
                        dataIndex: 'CATEG',
                        width: '200px',
                        style: 'padding-left:  1em;'
                    }
                ],
                listItemId: 'censusfreezelistX',
                categIndentPct: '0',
                colNumberToTruncateForIndents: 0,
                includeFooterLevels: false,
                categDepthColors: true,
                categDepthColorsArr: [
                    '#904848',
                    '#dddddd',
                    'white'
                ],
                defaultCollapseLevel: 2,
                helpHtml: './resources/html/CensusFreezeExample.html',
                arrowPctWidth: '6',
                linkedGridsParentItemId: 'censusFreezeCont',
                linkedGridsArr: [
                    {
                        itemId: 'censusfreeze'
                    }
                ],
                categCssArr: [
                    'touchtreegrid-list-categ0',
                    'touchtreegrid-list-categ1',
                    'touchtreegrid-list-categ'
                ],
                hideExpandCollapseBtns: true,
                cls: [
                    'x-touchtreegrid-list',
                    'x-touchtreegrid-list-censusmaine'
                ],
                itemId: 'censusfreezeX',
                minWidth: '220px',
                style: 'border-right: 2px solid gray;',
                width: '220px'
            },
            {
                xtype: 'container',
                flex: 1,
                layout: 'hbox',
                scrollable: {
                    direction: 'horizontal',
                    directionLock: true
                },
                items: [
                    {
                        xtype: 'touchtreegrid',
                        store: 'censusFreezeStore',
                        onItemDisclosure: false,
                        listItemId: 'censusfreezelist',
                        categIndentPct: '0',
                        colNumberToTruncateForIndents: 0,
                        includeFooterLevels: true,
                        defaultCollapseLevel: 2,
                        helpHtml: './resources/html/CensusFreezeExample.html',
                        arrowPctWidth: '0',
                        linkedGridsParentItemId: 'censusFreezeCont',
                        linkedGridsArr: [
                            {
                                itemId: 'censusfreezeX'
                            }
                        ],
                        hideExpandCollapseBtns: false,
                        categCssArr: [
                            'touchtreegrid-list-categ0',
                            'touchtreegrid-list-categ1',
                            'touchtreegrid-list-categ'
                        ],
                        flex: 1,
                        cls: [
                            'x-touchtreegrid-list',
                            'x-touchtreegrid-list-censusmaine'
                        ],
                        itemId: 'censusfreeze',
                        minWidth: '2520px',
                        width: '2520px'
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        var device = ((Ext.os.is.Phone) ? 'phone' : 'tablet');
        var orient = ((Ext.Viewport.getWindowWidth() > Ext.Viewport.getWindowHeight()) ? 'landscape' : 'portrait');


        if (device==='phone' && orient==='portrait') {
            var thisItem = this.down('#censusfreezeX');

            thisItem.setWidth('170px');
            thisItem.setMinWidth('170px');

            var colArr = thisItem.getColumns();
            colArr.width = '150px';
            thisItem.setColumns(colArr);
        }


    }

});