/*
 * File: app/view/MainContainer.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.MainContainer', {
    extend: 'Ext.Container',
    alias: 'widget.mainContainer',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Img',
        'Ext.Menu'
    ],

    config: {
        layout: 'hbox',
        items: [
            {
                xtype: 'container',
                flex: 1,
                itemId: 'menucontgridpanel',
                width: '100%',
                layout: 'fit',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: 'menuconttoolbardark',
                        docked: 'top',
                        itemId: 'menuconttoolbar',
                        title: 'Accordion',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'menubtn',
                                padding: '0 .2em .3em .2em',
                                style: 'border: 1px solid grey; ',
                                ui: 'plain',
                                labelCls: 'x-button-label-menu',
                                text: 'MENU'
                            },
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: '1.5em',
                                hidden: false,
                                itemId: 'gridhelp',
                                margin: '.5em 0 0 0',
                                width: '1.5em',
                                src: './resources/images/question.png'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        itemId: 'menucontswap',
                        layout: 'card'
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'menuconthelppanel',
                minWidth: 0,
                style: 'border-left: 1px solid gray; background-color:#fffd8f;',
                layout: 'fit',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: 'menuconthelptoolbar',
                        docked: 'top',
                        itemId: 'menuconthelptoolbar',
                        ui: 'plain',
                        items: [
                            {
                                xtype: 'button',
                                iconMask: true,
                                itemId: 'closehelp',
                                margin: '0 0 .2em 0',
                                padding: '0 0 .2em 0',
                                iconCls: 'delete'
                            }
                        ]
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();
        if (!Ext.os.is.Phone) {
           this.down('#menuconthelptoolbar').setHidden(true);  // Hide help menu toolbar for tablets
        }
        //Ext.Viewport.toggleMenu('left');


    },

    myMenu: function() {
        var scrnHt = (window.innerHeight > 0) ? window.innerHeight : screen.height;
        var gridHt = scrnHt  - 35;  // - 32;  // FOOTER HIDDEN BELOW



        var items = [
        {
            xtype: 'container',
            itemId: 'menunav',
            minWidth: '256px',
            style: 'border-right: thin solid #999; background-color: #323232; font-size: 1em;',
            layout: {
                type: 'fit'
            },
            items: [
            {
                xtype: 'container',
                cls: 'menuopt_header',
                docked: 'top',
                height: '35px',
                html: 'TouchTreeGrid Demo',
                itemId: 'menuopt_header',
                maxHeight: '35px',
                minHeight: '35px',
                padding: '8px 0 0 0',
                style: 'color: white; text-align: center; font-size: 1em;',
                ui: 'plain'
            },
            {
                xtype: 'container',
                minHeight: gridHt+'px',
                maxHeight: gridHt+'px',
                height: gridHt+'px',
                itemId: 'menuoptitems',
                style: 'background-color: #323232;',
                scrollable: {
                    //http://www.sencha.com/forum/showthread.php?175065
                    direction: 'vertical',
                    directionLock: true,
                    momentumEasing: {
                        momentum: {
                            acceleration: 30,
                            friction: 0.5
                        },
                        bounce: {
                            acceleration: 0.0001,
                            springTension: 0.9999
                        },
                        minVelocity: 5
                    },
                    outOfBoundRestrictFactor: 0
                },
                items: [
                {
                    xtype: 'touchtreegrid',
                    store: 'menuOptsStore',
                    listScrollable: false,
                    disableSelection: false,
                    onItemDisclosure: true,
                    columns: [
                    {
                        dataIndex: 'Image',
                        width: '15%',
                        style: 'text-align: left;'
                    },
                    {
                        dataIndex: 'Text',
                        width: '85%',
                        style: 'text-align: left;'
                    }
                    ],
                    disclosureProperty: 'leaf',
                    listItemId: 'menuoptlist',
                    includeFooter: false,
                    categIndentPct: '0',
                    categDepthColors: true,
                    categDepthColorsArr: [
                    '#323232',
                    'white',
                    'white'
                    ],
                    includeHeader: false,
                    applyDefaultCollapseLevel: true,
                    disableExpandCollapse: true,
                    singleExpand: false,
                    mode: 'MULTI',
                    arrowPctWidth: '0',
                    cls: [
                    'x-touchtreegrid-list',
                    'x-touchtreegrid-list-menuopt'
                    ],
                    minHeight: '68em',
                    height: '68em',
                    maxHeight: '68em',
                    itemId: 'menuopt'
                }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                itemId: 'menuopt_footer',
                maxHeight: '32px',
                minHeight: '32px',
                hidden: true,     // **********************************  CUSTOM SETTING
                style: ' background-color: #323232; ',
                ui: 'plain',
                items: [
                {
                    xtype: 'image',
                    docked: 'left',
                    height: '32px',
                    itemId: 'menuoptexpand',
                    margin: '0 0 8px 0',
                    width: '32px',
                    src: './resources/images/bullet_arrow_bottom.png'
                },
                {
                    xtype: 'image',
                    docked: 'left',
                    height: '32px',
                    itemId: 'menuoptcollapse',
                    margin: '0 0 8px 0',
                    width: '32px',
                    src: './resources/images/bullet_arrow_top.png'
                }
                ]
            }
            ]
        }];
        return items;
    },

    menuForSide: function(side) {
        var items = this.myMenu();

        var className = 'Ext.Menu';
        if (Ext.theme.name == "Blackberry") {
            if (['top', 'bottom'].indexOf(side) != -1) {
                className = 'Ext.ux.ApplicationMenu';
            } else {
                className = 'Ext.ux.ContextMenu';
            }
        }

        return Ext.create(className, {
            baseCls: 'x-menu-touchtreegrid',   // Override baseCls so that we can remove 0 padding, etc...
            items: items
        });
    },

    doSetHidden: function(hidden) {
        this.callParent(arguments);

        if (hidden) {
            Ext.Viewport.removeMenu('left');
        } else {

            Ext.Viewport.setMenu(this.menuForSide('left'), {  // slide
                side: 'left',
                cover: false
            });

        }

    }

});