/*
 * File: app/model/Census.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.model.Census', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'CATEG',
                type: 'string'
            },
            {
                name: 'ID'
            },
            {
                name: 'PARENT_ID'
            },
            {
                name: 'TotalPopulation'
            },
            {
                name: 'Male'
            },
            {
                name: 'Female'
            },
            {
                name: 'Under5years'
            },
            {
                name: 'Age5to9'
            },
            {
                name: 'Age10to14'
            },
            {
                name: 'Age15to19'
            },
            {
                name: 'Age20to24'
            },
            {
                name: 'Age25to34'
            },
            {
                name: 'Age35to44'
            },
            {
                name: 'Age45to54'
            },
            {
                name: 'Age55to59'
            },
            {
                name: 'Age60to64'
            },
            {
                name: 'Age65to74'
            },
            {
                name: 'Age75to84'
            },
            {
                name: 'Age85andOver'
            },
            {
                name: 'MedianAge'
            },
            {
                name: 'Age18andOver'
            },
            {
                name: 'Age18andOverMale'
            },
            {
                name: 'Age18andOverFemale'
            },
            {
                name: 'Age21andOver'
            },
            {
                name: 'Age62andOver'
            },
            {
                name: 'Age65andOver'
            },
            {
                name: 'Age65andOverMale'
            },
            {
                name: 'Age65andOverFemale'
            }
        ]
    }
});