/*
 * File: app/view/CategCont.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.CategCont', {
    extend: 'Ext.Container',
    alias: 'widget.categCont',

    requires: [
        'Ext.Container'
    ],

    config: {
        layout: 'fit',
        items: [
            {
                xtype: 'touchtreegrid',
                store: 'myTreeStore',
                columns: [
                    {
                        header: 'Category',
                        dataIndex: 'CATEG',
                        width: '100%',
                        style: 'padding-left:  .2em;'
                    }
                ],
                header: {
                    maxHeight: '29px',
                    minHeight: '29px'
                },
                listItemId: 'categlist',
                includeFooter: false,
                categIndentPct: '2',
                defaultCollapseLevel: 2,
                arrowPctWidth: '4',
                categCssArr: [
                    'touchtreegrid-list-categ0',
                    'touchtreegrid-list-categ1',
                    'touchtreegrid-list-categ2',
                    'touchtreegrid-list-categ3',
                    'touchtreegrid-list-categ4',
                    'touchtreegrid-list-categ5',
                    'touchtreegrid-list-categ6',
                    'touchtreegrid-list-categ7',
                    'touchtreegrid-list-categ8'
                ],
                cls: [
                    'x-touchtreegrid-list',
                    'x-touchtreegrid-list-censusmaine'
                ],
                itemId: 'categ'
            }
        ]
    }

});