/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.Main', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.main',

    requires: [
        'TouchTreeGrid.view.MyFormPanel2',
        'Ext.TitleBar',
        'Ext.form.Panel',
        'Ext.field.Radio',
        'Ext.Label',
        'Ext.tab.Bar'
    ],

    config: {
        itemId: 'main',
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                itemId: 'maintitlebar',
                minHeight: '2.2em',
                title: 'TouchTreeGrid - Forms'
            },
            {
                xtype: 'container',
                title: 'Grid Edit',
                iconCls: 'home',
                itemId: 'gridEdit',
                layout: 'fit',
                items: [
                    {
                        xtype: 'touchtreegrid',
                        store: 'Task',
                        columns: [
                            {
                                header: 'Task',
                                dataIndex: 'text',
                                width: '100%',
                                style: ' text-align: left;',
                                categStyle: 'font-weight: bold; text-align: left; color: blue;',
                                headerStyle: 'text-align: left; color: #ccc;'
                            }
                        ],
                        variableHeights: true,
                        listItemId: 'firstexamplelist',
                        includeFooter: false,
                        contentItemTplOverride: '{[this.renderer_myForm("TouchTreeGrid.view.MyFormPanel", "320px", values)]}',
                        includeHeader: false,
                        applyDefaultCollapseLevel: false,
                        defaultCollapseLevel: 1,
                        singleExpand: true,
                        infinite: false,
                        cls: [
                            'x-touchtreegrid-list',
                            'touchtreegrid-myForm'
                        ],
                        itemId: 'firstexample'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Form Edit',
                iconCls: 'compose',
                cls: 'form-edit',
                itemId: 'formEdit',
                layout: 'card',
                items: [
                    {
                        xtype: 'touchtreegrid',
                        store: 'Task2',
                        columns: [
                            {
                                header: 'Task',
                                dataIndex: 'text',
                                width: '100%',
                                style: ' text-align: left;',
                                categStyle: 'font-weight: bold; text-align: left; color: blue;',
                                headerStyle: 'text-align: left; color: #ccc;'
                            }
                        ],
                        variableHeights: true,
                        listItemId: 'example2list',
                        includeFooter: false,
                        contentItemTplOverride: '{[this.renderer_myForm("TouchTreeGrid.view.MyFormPanel2", "320px", values)]}',
                        includeHeader: false,
                        applyDefaultCollapseLevel: false,
                        defaultCollapseLevel: 1,
                        singleExpand: true,
                        infinite: false,
                        cls: [
                            'x-touchtreegrid-list',
                            'touchtreegrid-myForm',
                            'touchtreegrid-myForm-animate'
                        ],
                        itemId: 'example2'
                    },
                    {
                        xtype: 'myFormPanel2',
                        itemId: 'myFormPanel2Edit'
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Multi',
                iconCls: 'multi',
                itemId: 'multiForms',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'touchtreegrid',
                        store: 'Task',
                        columns: [
                            {
                                header: 'Task',
                                dataIndex: 'text',
                                width: '100%',
                                style: ' text-align: left;',
                                categStyle: 'font-weight: bold; text-align: left; color: blue;',
                                headerStyle: 'text-align: left; color: #ccc;'
                            }
                        ],
                        variableHeights: true,
                        listItemId: 'multiexamplelist',
                        includeFooter: false,
                        contentItemTplOverride: '{[this.scope.config.formType===\'short\' ? this.renderer_myForm("TouchTreeGrid.view.MyFormPanel", "320px", values) : this.renderer_myForm("TouchTreeGrid.view.MyFormPanelLong", "420px", values)]}',
                        includeHeader: false,
                        applyDefaultCollapseLevel: false,
                        defaultCollapseLevel: 1,
                        singleExpand: true,
                        infinite: false,
                        formType: 'short',
                        flex: 1,
                        cls: [
                            'x-touchtreegrid-list',
                            'touchtreegrid-myForm'
                        ],
                        itemId: 'multiexample'
                    },
                    {
                        xtype: 'toolbar',
                        cls: 'multiexample-toolbar',
                        docked: 'bottom',
                        maxHeight: '2.6em',
                        ui: 'light',
                        items: [
                            {
                                xtype: 'radiofield',
                                itemId: 'shortFormType',
                                width: '8em',
                                label: 'Short Form',
                                labelWidth: 'auto',
                                name: 'formType',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                itemId: 'longFormType',
                                width: '5em',
                                label: 'Long Form',
                                labelWidth: 'auto',
                                name: 'formType'
                            },
                            {
                                xtype: 'label',
                                flex: 1
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: 'Multi-Mxd',
                iconCls: 'more',
                itemId: 'multiFormsByRecord',
                layout: 'fit',
                items: [
                    {
                        xtype: 'touchtreegrid',
                        store: 'TaskMultiRec',
                        columns: [
                            {
                                header: 'Task',
                                dataIndex: 'text',
                                width: '100%',
                                style: ' text-align: left;',
                                categStyle: 'font-weight: bold; text-align: left; color: blue;',
                                headerStyle: 'text-align: left; color: #ccc;',
                                renderer: 'this.renderer_CategText(values)'
                            }
                        ],
                        variableHeights: true,
                        listItemId: 'multireclist',
                        includeFooter: false,
                        renderers: {
                            renderer_multiFormRec: function (values) {
                            if (values.formType === 'mini'){
                               return this.renderer_myForm("TouchTreeGrid.view.MyFormPanelMini", "160px", values)
                            }
                            else if (values.formType === 'long'){
                               return this.renderer_myForm("TouchTreeGrid.view.MyFormPanelLong", "420px", values)
                            }
                            else {
                               return this.renderer_myForm("TouchTreeGrid.view.MyFormPanel", "320px", values);
                            }
                        },
                            renderer_CategText: function (values){
                        return values.text + ' (' + values.categType + ')';
                        }
                        },
                        contentItemTplOverride: '{[this.renderer_multiFormRec(values)]}',
                        includeHeader: false,
                        applyDefaultCollapseLevel: false,
                        defaultCollapseLevel: 1,
                        singleExpand: true,
                        infinite: false,
                        cls: [
                            'x-touchtreegrid-list',
                            'touchtreegrid-myForm'
                        ],
                        itemId: 'multirec'
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onShortFormTypeCheck',
                event: 'check',
                delegate: '#shortFormType'
            },
            {
                fn: 'onLongFormTypeCheck',
                event: 'check',
                delegate: '#longFormType'
            },
            {
                fn: 'onMainActiveItemChange',
                event: 'activeitemchange'
            }
        ]
    },

    onShortFormTypeCheck: function(checkboxfield, e, eOpts) {
        var multiexample = checkboxfield.up('#multiForms').down('#multiexample');
        if (multiexample){
            multiexample.config.formType='short';
            multiexample.doRefreshList(true);
        }
    },

    onLongFormTypeCheck: function(checkboxfield, e, eOpts) {
        var multiexample = checkboxfield.up('#multiForms').down('#multiexample');
        if (multiexample){
            multiexample.config.formType='long';
            multiexample.doRefreshList(true);
        }
    },

    onMainActiveItemChange: function(container, value, oldValue, eOpts) {
        // Ensure all grids are loaded for mobile scenarios
        value.down('touchtreegrid').doRefreshList(true);
    }

});