/*
 * File: app/view/MyFormPanel2.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.MyFormPanel2', {
    extend: 'Ext.form.Panel',
    alias: 'widget.myFormPanel2',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.FieldSet',
        'Ext.field.TextArea',
        'Ext.field.Select',
        'Ext.Label',
        'Ext.field.Radio',
        'Ext.Spacer',
        'Ext.MessageBox'
    ],

    config: {
        readOnly: true,
        cls: 'myForm',
        itemId: 'myFormPanel2',
        maxWidth: '30em',
        style: 'font-size: .8rem;',
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                hidden: true,
                itemId: 'myForm2Toolbar',
                ui: 'plain',
                layout: {
                    type: 'hbox',
                    pack: 'end'
                },
                items: [
                    {
                        xtype: 'button',
                        cls: 'myform-edit-btn',
                        docked: 'left',
                        hidden: false,
                        itemId: 'myForm2BackBtn',
                        style: 'padding-top: 1px;',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'button',
                        cls: 'myform-edit-btn',
                        docked: 'right',
                        hidden: false,
                        itemId: 'myForm2RevertBtn',
                        style: 'padding-top: 2px;',
                        ui: 'plain',
                        text: 'Revert'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: '',
                items: [
                    {
                        xtype: 'container',
                        style: 'border-bottom: 1px solid #ddd;',
                        layout: {
                            type: 'hbox',
                            align: 'center'
                        },
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Task:',
                                labelWidth: '4em',
                                name: 'text'
                            },
                            {
                                xtype: 'button',
                                cls: 'myform-edit-btn',
                                docked: 'right',
                                itemId: 'myForm2EditBtn',
                                style: 'padding-top: 5px; margin: 5px 10px 0 0;',
                                ui: 'plain',
                                text: 'Edit>>'
                            }
                        ]
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Comment:',
                        labelWidth: '5.7rem',
                        name: 'comment',
                        maxRows: 2
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'myselectfield2',
                        label: 'Select',
                        name: 'option',
                        options: [
                            {
                                text: 'First Option',
                                value: null
                            },
                            {
                                text: 'Second Option',
                                value: 'second'
                            },
                            {
                                text: 'Third Option',
                                value: 'third'
                            }
                        ],
                        usePicker: false
                    },
                    {
                        xtype: 'container',
                        height: '35px',
                        style: 'border-bottom: 1px solid #ddd;',
                        layout: {
                            type: 'hbox',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'label',
                                flex: 1,
                                html: 'Radio',
                                style: 'padding: .6em 0 0 .6em; font-size: .8rem; font-weight: bold; color: #333;'
                            },
                            {
                                xtype: 'radiofield',
                                itemId: 'opt1',
                                style: 'border-bottom: none;',
                                width: '125px',
                                label: 'Opt1',
                                labelWidth: '65px',
                                name: 'myRadioBtn',
                                checked: true
                            },
                            {
                                xtype: 'radiofield',
                                itemId: 'opt2',
                                style: 'border-bottom: none;',
                                width: '125px',
                                label: 'Opt2',
                                labelWidth: '65px',
                                name: 'myRadioBtn'
                            },
                            {
                                xtype: 'spacer',
                                width: 20
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: 'TEST LABEL',
                        style: 'padding-left: .6em; color: red; font-weight: bold;'
                    },
                    {
                        xtype: 'container',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'container',
                                flex: 1,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        label: 'Check1',
                                        labelAlign: 'right',
                                        labelWidth: '5em',
                                        name: 'check1'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        label: 'Check2',
                                        labelAlign: 'right',
                                        labelWidth: '5em',
                                        name: 'check2'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        label: 'Check3',
                                        labelAlign: 'right',
                                        labelWidth: '5em',
                                        name: 'check3'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                items: [
                                    {
                                        xtype: 'checkboxfield',
                                        label: 'Check4',
                                        labelAlign: 'right',
                                        labelWidth: '5em',
                                        name: 'check4'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        label: 'Check5',
                                        labelAlign: 'right',
                                        labelWidth: '5em',
                                        name: 'check5'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        label: 'Check6',
                                        labelAlign: 'right',
                                        labelWidth: '5em',
                                        name: 'check6'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});