/*
 * File: app/view/matrixViewPhone.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CalendarPicker.view.matrixViewPhone', {
    extend: 'Ext.Container',
    alias: 'widget.matrixViewPhone',

    config: {
        cls: 'matrix-view',
        itemId: 'matrixViewPhone',
        style: 'background-color: white;',
        ui: 'light',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                ui: 'light',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'matrixViewBackBtn',
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'segmentedbutton',
                        itemId: 'matrixViewSegBtn',
                        items: [
                            {
                                xtype: 'button',
                                pressed: true,
                                itemId: 'matrixViewYearBtn',
                                text: 'Year'
                            },
                            {
                                xtype: 'button',
                                itemId: 'matrixViewListBtn',
                                text: 'List'
                            },
                            {
                                xtype: 'button',
                                itemId: 'matrixViewDayBtn',
                                text: 'Day'
                            }
                        ]
                    },
                    {
                        xtype: 'label',
                        html: '',
                        itemId: 'matrixViewLabel',
                        style: 'margin-left: 1em;'
                    }
                ]
            },
            {
                xtype: 'container',
                itemId: 'yearView',
                margin: '.5em',
                style: 'border: 1px solid blue;background-color: white;',
                layout: {
                    type: 'fit'
                }
            },
            {
                xtype: 'container',
                html: 'More Later...',
                itemId: 'listView',
                style: 'border: 1px solid blue; background-color: white;',
                layout: {
                    type: 'fit'
                }
            },
            {
                xtype: 'container',
                itemId: 'dayView',
                maxWidth: '40em',
                style: 'background-color: white; border: 1px solid gray; margin: .5em;',
                layout: {
                    type: 'vbox'
                },
                items: [
                    {
                        xtype: 'container',
                        height: '10em',
                        style: 'border-bottom: 1px solid gray; margin: 0 1em 0 1em;',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'container',
                                flex: 1,
                                itemId: 'dayViewMoCal',
                                width: '17em',
                                layout: {
                                    type: 'fit'
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        listeners: {
                            swipe: {
                                fn: function(e) {
                                      this.up('#dayView').fireEvent('dayViewSwipe', this.up('#dayView'), e);
                                  },
                                element: 'element'
                            }
                        },
                        flex: 1,
                        html: 'List detail for selected day...',
                        itemId: 'dayViewListDetail',
                        style: 'border: solid 1px gray; margin: 1em .5em 1em .5em; ',
                        styleHtmlCls: 'dayViewListDetail-html',
                        styleHtmlContent: true
                    }
                ]
            }
        ]
    }

});