/*
 * File: app/controller/DateExamplesController.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CalendarPicker.controller.DateExamplesController', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            overlayPanel: {
                autoCreate: true,
                selector: 'overlayPanel',
                xtype: 'overlayPanel'
            },
            dateexamples: {
                selector: 'dateexamples',
                xtype: 'dateexamples'
            }
        },

        control: {
            "container": {
                checkin: 'onExample1CheckIn',
                checkout: 'onExample1Checkout',
                checkin2: 'onExample2Checkin',
                checkin2B: 'onExample2BCheckin',
                multisel_btn: 'onExample3_Multisel',
                lookup_btn: 'onExample4_Lookup',
                filter_btn: 'onExample5_December',
                day_count_btn: 'onExample6_DayCount',
                optionDates_btn: 'onExample7_OptionDates'
            },
            "container#calendar_checkin": {
                calendarClosed: 'onExample1CheckInClosed'
            },
            "container#calendar_checkout": {
                calendarClosed: 'onExample1CheckOutClosed'
            },
            "container#calendar_checkin2": {
                calendarClosed: 'onExample2CheckinClosed'
            },
            "container#calendar_checkin2B": {
                calendarClosed: 'onExample2BCheckinClosed'
            },
            "textfield#sel_date": {
                sel_date: 'onExample2C_Textfield'
            },
            "container#calendar_sel_date": {
                calendarClosed: 'onExample2C_TextfieldClosed'
            },
            "container#calendar_multi": {
                calendarClosed: 'onExample3_MultiselClosed'
            },
            "container#calendar_lookup": {
                dateSelected: 'onExample4_LookupSelected',
                calendarClosed: 'onExample4_LookupClosed'
            },
            "container#calendar_filter": {
                calendarClosed: 'onExample5_DecemberClosed'
            },
            "container#calendar_daycount": {
                calendarClosed: 'onExample6_DaycountClosed'
            },
            "container#calendar_optionDates": {
                calendarClosed: 'onExample7_OptionDatesClosed'
            }
        }
    },

    onExample1CheckIn: function(container) {
        var returnItem = this.getDateexamples().down('#example1');
        var lastSelDt = returnItem.down('#checkin_btn').lastSelectedDate;

        var selDts=(Ext.isEmpty(lastSelDt) ? [] : [lastSelDt]), disableDts=[];
        var checkOutDt = returnItem.down('#checkout_btn').lastSelectedDate;
        if (!Ext.isEmpty(checkOutDt)) {
            // disabled checkkou date if defined
            selDts.push(checkOutDt);
            disableDts.push(checkOutDt);

        }

        var getDts = Ext.create('widget.calendarpicker', {
            title : 'Choose Check In',
            itemId : 'calendar_checkin',
            customCls : ['calendarpicker-kayak'],
            selectMode: 'SINGLE',
            backMonths: 0,
            forwardMonths: 12,
            autoCollapseMonthsPriorToMinSelDt: true,
            useIconsForExpCollapse: false,
            disablePastDates: true,
            holidayDtArr: ['2013-01-01', '2013-01-21', '2013-02-18', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17'],
            returnItem: returnItem,
            selDtArr: selDts,
            disableDtArr: disableDts,
            singleExpand: true,
            defaultCollapseLevel: 1,
            height: '100%',
            width: '100%'
        });

        var overPnl = this.getOverlayPanel();
        overPnl.add(getDts);
        overPnl.showBy(container);



    },

    onExample1CheckInClosed: function(calendarpicker) {
        var selDts = calendarpicker.getSelDtArr();
        var lastSelDt = calendarpicker.getLastSelectedDate();
        if (!Ext.isEmpty(lastSelDt)) {
            var returnItem=calendarpicker.getReturnItem();
            var day = Ext.Date.parse(lastSelDt, 'Y-m-d');

            var day_html = returnItem.down('#checkin_day');
            day_html.setHtml(Ext.Date.format(day, 'j')); 
            day_html.addCls('kayak-button-day');
            day_html.removeCls('kayak-button-select');

            var other_html = returnItem.down('#checkin_dayname_month');
            other_html.setHtml(Ext.Date.format(day, 'D')+'<br>'+Ext.Date.format(day, 'M')); 

            returnItem.down('#checkin_btn').lastSelectedDate = lastSelDt;

            // clear checkout date if new checkin date is changed to after it
            var out = returnItem.down('#checkout_btn');

            if (out) {
                day_html = out.down('#checkout_day');        
                if (out.lastSelectedDate < lastSelDt) {   
                    out.lastSelectedDate = '';
                    day_html.setHtml('Select');
                    day_html.addCls('kayak-button-select');

                    other_html = out.down('#checkout_dayname_month');
                    other_html.setHtml(''); 
                } else {
                    if (!Ext.isEmpty(out.lastSelectedDate)) {
                        //       day_html.removeCls('kayak-button-select');
                    }
                }
            }
        }
        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    },

    onExample1Checkout: function(container) {
        var returnItem = this.getDateexamples().down('#example1');
        var lastSelDt = returnItem.down('#checkout_btn').lastSelectedDate;

        var back=0, fwd=12, selDts=(Ext.isEmpty(lastSelDt) ? [] : [lastSelDt]), disableDts=[];
        var checkInDt = returnItem.down('#checkin_btn').lastSelectedDate;
        if (!Ext.isEmpty(checkInDt)) {
            // disabled all dates on and prior to check in date (for that month)
            // and mark checkin date as selected
            selDts.push(checkInDt);

            var inActDt = Ext.Date.parse(checkInDt, 'Y-m-d');
            var inFirstDt = Ext.Date.clearTime(Ext.Date.getFirstDateOfMonth(inActDt), true);

            var today= Ext.Date.clearTime(new Date(Date(Ext.Date.now())), true);
            var currFirstDt = Ext.Date.clearTime(Ext.Date.getFirstDateOfMonth(today), true);

            var modiff = Ext.Date.diff(currFirstDt, inFirstDt, Ext.Date.MONTH);
            back = -1*modiff;

            var tmpDt = inActDt, tmpDt2;
            do {
                disableDts.push(Ext.Date.format(tmpDt, 'Y-m-d'));

                tmpDt2 = Ext.Date.clone(tmpDt);
                tmpDt = Ext.Date.add(tmpDt, Ext.Date.DAY, -1);  // next day
                if (Ext.Date.format(tmpDt2, 'Y-m-d')===Ext.Date.format(tmpDt, 'Y-m-d')) {
                    // Correct for day light savings changes were add() method only adds 23 hours
                    tmpDt = Ext.Date.add(tmpDt, Ext.Date.DAY, -1);  // next day
                }
                Ext.Date.clearTime(tmpDt);        

            } while (tmpDt >= inFirstDt);
        }



        var getDts = Ext.create('widget.calendarpicker', {
            //   xtype: 'calendarpicker',
            title : 'Choose Check Out',
            itemId : 'calendar_checkout',
            customCls : ['calendarpicker-kayak'],
            selectMode: 'SINGLE',
            backMonths: back,
            forwardMonths: fwd,
            useIconsForExpCollapse: false,
            disablePastDates: true,    
            holidayDtArr: ['2013-01-01', '2013-01-21', '2013-02-18', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17'],
            includeCustomFooterItems: false,
            returnItem: returnItem,
            selDtArr : selDts,
            disableDtArr: disableDts,
            height: '100%',
            width: '100%'
        });

        var overPnl = this.getOverlayPanel();
        overPnl.add(getDts);


        overPnl.showBy(container);


    },

    onExample1CheckOutClosed: function(calendarpicker) {
        var selDts = calendarpicker.getSelDtArr();
        var lastSelDt = calendarpicker.getLastSelectedDate();
        if (!Ext.isEmpty(lastSelDt)) {
            var returnItem=calendarpicker.getReturnItem();
            var day = Ext.Date.parse(lastSelDt, 'Y-m-d');

            var day_html = returnItem.down('#checkout_day');
            day_html.setHtml(Ext.Date.format(day, 'j')); 
            day_html.addCls('kayak-button-day');
            day_html.removeCls('kayak-button-select');    

            var other_html = returnItem.down('#checkout_dayname_month');
            other_html.setHtml(Ext.Date.format(day, 'D')+'<br>'+Ext.Date.format(day, 'M')); 

            returnItem.down('#checkout_btn').lastSelectedDate = lastSelDt;
        }

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    },

    onExample2Checkin: function(container) {
        var returnItem = this.getDateexamples().down('#example2');
        var selDtArr = returnItem.down('#checkin_btn2').selDtArr;

        var selDts=(Ext.isEmpty(selDtArr) ? [] : selDtArr), disableDts=[];

        var getDts = Ext.create('widget.calendarpicker', {
            //     xtype: 'calendarpicker',
            title : 'Check In / Check Out',
            itemId : 'calendar_checkin2',
            customCls : ['calendarpicker-kayak'],
            selectMode: 'RANGE',
            backMonths: 0,
            forwardMonths: 12,
            autoCollapseMonthsPriorToMinSelDt: true,
            useIconsForExpCollapse: true,
            disablePastDates: true,
            holidayDtArr: ['2013-01-01', '2013-01-21', '2013-02-18', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17'],
            includeCustomFooterItems: true,
            returnItem: returnItem,
            defaultCollapseLevel: 99,
            selDtArr: selDts,
            disableDtArr: disableDts,
            height: '100%',
            width: '100%'
        });

        var overPnl = this.getOverlayPanel();
        overPnl.add(getDts);

        overPnl.showBy(container);


    },

    onExample2CheckinClosed: function(calendarpicker) {
        var returnItem=calendarpicker.getReturnItem();
        var day_html = returnItem.down('#checkin_day2');
        var other_html = returnItem.down('#checkin_dayname_month2');
        var day_html2 = returnItem.down('#checkout_day2');
        var other_html2 = returnItem.down('#checkout_dayname_month2');

        var selDts = calendarpicker.getSelDtArr();
        returnItem.down('#checkin_btn2').selDtArr = selDts;

        day_html.removeCls('kayak-button-select');  
        day_html2.removeCls('kayak-button-select');

        if (Ext.isEmpty(selDts)) {
            day_html.setHtml('Select');
            day_html2.setHtml('Select');
            other_html.setHtml(''); 
            other_html2.setHtml(''); 
            day_html.addCls('kayak-button-select');  // show select button
            day_html2.addCls('kayak-button-select');
        } else {       
            var maxDt = Ext.Array.max(selDts);
            var minDt = Ext.Array.min(selDts);   

            var minDay = Ext.Date.parse(minDt, 'Y-m-d');
            var maxDay = Ext.Date.parse(maxDt, 'Y-m-d');


            day_html.setHtml(Ext.Date.format(minDay, 'j')); 
            day_html2.setHtml(Ext.Date.format(maxDay, 'j')); 

            day_html.addCls('kayak-button-day');
            day_html2.addCls('kayak-button-day');


            other_html.setHtml(Ext.Date.format(minDay, 'D')+'<br>'+Ext.Date.format(minDay, 'M')); 
            other_html2.setHtml(Ext.Date.format(maxDay, 'D')+'<br>'+Ext.Date.format(maxDay, 'M'));     
        }    

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    },

    onExample2BCheckin: function(container) {
        var returnItem = this.getDateexamples().down('#example2B');
        var selDtArr = returnItem.down('#checkin_btn2B').selDtArr;
        var backMonths = (Ext.isEmpty(returnItem.backMonths) ? 0 : returnItem.backMonths);
        var forwardMonths = (Ext.isEmpty(returnItem.forwardMonths) ? 12 : returnItem.forwardMonths);


        var selDts=(Ext.isEmpty(selDtArr) ? [] : selDtArr), disableDts=[];

        var scrnwid = (window.innerWidth > 0) ? window.innerWidth : screen.width;  // get screen width
        var maxwid = ((Ext.os.is.Phone) ? scrnwid : 17*16);
        var itemHt = maxwid/7;

        var getDts = Ext.create('widget.calendarpicker', {
            //     xtype: 'calendarpicker',
            title : 'Check In / Check Out',
            itemId : 'calendar_checkin2B',
            customCls : ['calendarpicker-ios'],
            selectMode: 'RANGE',
            backMonths: backMonths,
            forwardMonths: forwardMonths,
            itemHeight: 16,   // Set minimum value for weedday names row ... use css for other heights
            variableHeights: true,
            autoCollapseMonthsPriorToMinSelDt: true,
            autoExpandMonthsWithSelDates: true,    
            useIconsForExpCollapse: true,
            disablePastDates: true,
            holidayDtArr: ['2013-01-01', '2013-01-21', '2013-02-18', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17'],
            includeCustomFooterItems: true,
            returnItem: returnItem,
            defaultCollapseLevel: 0,
            selDtArr: selDts,
            disableDtArr: disableDts,
            height: '100%',
            width: '100%',
            allowMonthAdditions: true,
            monthsToAppend: 3,
            monthsToInsert: 0
        });

        var overPnl = this.getOverlayPanel();
        overPnl.setMaxWidth('17em');  // Prevent resizing for Phone landscape
        overPnl.setModal({ transparent: true });  // Keep background transaparent instead of gray since IOS calendar is already gray
        overPnl.add(getDts);

        overPnl.showBy(container);




    },

    onExample2BCheckinClosed: function(calendarpicker) {
        var returnItem=calendarpicker.getReturnItem();

        // Save any updates to backMonths or forwardMonths
        returnItem.backMonths = calendarpicker.getBackMonths();
        returnItem.forwardMonths = calendarpicker.getForwardMonths();

        var day_html = returnItem.down('#checkin_day2B');
        var other_html = returnItem.down('#checkin_dayname_month2B');
        var day_html2 = returnItem.down('#checkout_day2B');
        var other_html2 = returnItem.down('#checkout_dayname_month2B');

        var selDts = calendarpicker.getSelDtArr();
        returnItem.down('#checkin_btn2B').selDtArr = selDts;

        day_html.removeCls('kayak-button-select');  
        day_html2.removeCls('kayak-button-select');

        if (Ext.isEmpty(selDts)) {
            day_html.setHtml('Select');
            day_html2.setHtml('Select');
            other_html.setHtml(''); 
            other_html2.setHtml(''); 
            day_html.addCls('kayak-button-select');  // show select button
            day_html2.addCls('kayak-button-select');
        } else {       
            var maxDt = Ext.Array.max(selDts);
            var minDt = Ext.Array.min(selDts);   

            var minDay = Ext.Date.parse(minDt, 'Y-m-d');
            var maxDay = Ext.Date.parse(maxDt, 'Y-m-d');


            day_html.setHtml(Ext.Date.format(minDay, 'j')); 
            day_html2.setHtml(Ext.Date.format(maxDay, 'j')); 

            day_html.addCls('kayak-button-day');
            day_html2.addCls('kayak-button-day');


            other_html.setHtml(Ext.Date.format(minDay, 'D')+'<br>'+Ext.Date.format(minDay, 'M')); 
            other_html2.setHtml(Ext.Date.format(maxDay, 'D')+'<br>'+Ext.Date.format(maxDay, 'M'));     
        }    

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.setModal({ transparent: false });  // Reset transparancy for next use
        overPnl.setMaxWidth((Ext.os.is.Phone) ? '' : '17em');  // reset since changed for this example
        overPnl.hide();
    },

    onExample2C_Textfield: function(textfield) {
        var returnItem = this.getDateexamples().down('#sel_date');
        var lastSelDt = returnItem.lastSelectedDate;
        var backMonths = (Ext.isEmpty(returnItem.backMonths) ? 3 : returnItem.backMonths);
        var forwardMonths = (Ext.isEmpty(returnItem.forwardMonths) ? 0 : returnItem.forwardMonths);

        var selDts=(Ext.isEmpty(lastSelDt) ? [] : [lastSelDt]), disableDts=[];

        // Add CLEAR button to allow user to remove date (later figure out how to leverage clearIcon on textfield)
        myCustomBtns = {
            xtype: 'segmentedbutton',
            itemId : 'pickerfooterbtns',
            docked : 'right',
            items: [
            {
                xtype: 'button',
                text: 'CLEAR',
                iconCls: '',
                cls: 'pickerfooterbtns',
                listeners : {
                    tap: function (button, e, options) {
                        this.up('calendarpicker').customBtns('CLEAR');    // Clear data            
                        this.up('calendarpicker').customBtns('DONE');     // Then fire event to close calendar
                    }
                }
            },
            {
                xtype: 'button',
                text: 'Cancel',
                iconCls: '',
                cls: 'pickerfooterbtns',
                listeners : {
                    tap: function (button, e, options) {
                        this.up('calendarpicker').customBtns('CANCEL');    // Clear data            
                    }
                }
            }

        ]};

        var getDts = Ext.create('widget.calendarpicker', {
            title : 'Select As-Of Date',
            itemId : 'calendar_sel_date',
            customCls : ['calendarpicker-ios'],
            selectMode: 'SINGLE',
            backMonths: backMonths,
            forwardMonths: forwardMonths,
            disableFutureDates: true,
            itemHeight: 16,   // Set minimum value for weekday names row ... use css for other heights
            variableHeights: true,
            autoCollapseMonthsPriorToMinSelDt: true,
            useIconsForExpCollapse: false,
            holidayDtArr: ['2013-01-01', '2013-01-21', '2013-02-18', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17'],
            returnItem: returnItem,
            selDtArr: selDts,
            disableDtArr: disableDts,
            singleExpand: true,
            defaultCollapseLevel: 1,
            includeCustomFooterItems: true,    
            customFooterItems: myCustomBtns,
            height: '100%',
            width: '100%',
            allowMonthAdditions: true,
            monthsToAppend: 0,
            monthsToInsert: 3
        });
        getDts.setLastSelectedDate(lastSelDt);  // Needed for single select where user can cancel after navigating back

        var overPnl = this.getOverlayPanel();
        overPnl.add(getDts);
        overPnl.showBy(textfield);

    },

    onExample2C_TextfieldClosed: function(calendarpicker) {
        var returnItem=calendarpicker.getReturnItem();
        var selDts = calendarpicker.getSelDtArr();
        var lastSelDt = calendarpicker.getLastSelectedDate();
        returnItem.lastSelectedDate = lastSelDt;  // Needed for single select where user can cancel after navigating back

        // Save any updates to backMonths or forwardMonths
        returnItem.backMonths = calendarpicker.getBackMonths();
        returnItem.forwardMonths = calendarpicker.getForwardMonths();




        if (!Ext.isEmpty(lastSelDt)) {
            var day = Ext.Date.parse(lastSelDt, 'Y-m-d');
            returnItem.setValue(Ext.Date.format(day, 'm/d/Y'));
            returnItem.lastSelectedDate = lastSelDt;
        } else {
            returnItem.setValue('');
            returnItem.lastSelectedDate = '';
        }

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    },

    onExample3_Multisel: function(container) {
        var returnItem = this.getDateexamples().down('#example3');
        var selDtArr = returnItem.down('#multisel_btn').selDtArr;
        var initDtArr = ['2013-09-11', '2013-09-17', '2013-11-06'];

        var selDts=(Ext.isEmpty(selDtArr) ? initDtArr : selDtArr), disableDts=[];

        var getDts = Ext.create('widget.calendarpicker', {
            //     xtype: 'calendarpicker',
            title : 'Select Multiple Dates',
            itemId : 'calendar_multi',
            customCls : ['calendarpicker-kayak'],
            selectMode: 'MULTI',
            backMonths: 3,
            forwardMonths: 6,
            autoCollapseMonthsPriorToMinSelDt: true,
            useIconsForExpCollapse: true,
            disablePastDates: false,
            disableWeekends: true,
            disableHolidays: true,
            holidayDtArr: ['2013-01-01', '2013-01-21', '2013-02-18', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17'],
            includeCustomFooterItems: true,
            returnItem: returnItem,
            defaultCollapseLevel: 1,
            selDtArr: selDts,
            disableDtArr: disableDts,
            height: '100%',
            width: '100%'
        });

        var overPnl = this.getOverlayPanel();
        overPnl.add(getDts);

        overPnl.showBy(container);

    },

    onExample3_MultiselClosed: function(calendarpicker) {
        var returnItem=calendarpicker.getReturnItem();
        var multi_html = returnItem.down('#multisel_dates_html');

        var selDts = calendarpicker.getSelDtArr();
        returnItem.down('#multisel_btn').selDtArr = selDts;

        // sort array, build string and update html
        selDts.sort();
        multi_html.setHtml(selDts.join(', '));

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    },

    onExample4_Lookup: function(container) {
        var dateEx = this.getDateexamples();
        var returnItem = dateEx.down('#example4');
        var newcont = dateEx.down('#datePlanner');

        // Save title bar state and rename 
        var appTitle = dateEx.down('#appTitle');
        appTitle.origTitle = appTitle.getTitle()._title;
        appTitle.origUi = appTitle.getUi();
        appTitle.origCls = appTitle.getCls();

        appTitle.setTitle('Custom Calendar');
        appTitle.setUi('light');
        appTitle.setCls('');

        var planner_cal = newcont.down('#planner_cal');


        var holidayDtArr = ['2013-01-01', '2013-01-21', '2013-02-18', '2013-05-27', '2013-07-04', '2013-09-02', '2013-11-28', '2013-12-25', '2014-01-01', '2014-01-20', '2014-02-17'];

        myCustomBtns = {
            xtype: 'segmentedbutton',
            itemId : 'pickerfooterbtns',
            docked : 'right',
            items: [
            {
                xtype: 'button',
                text: 'RETURN',
                iconCls: '',
                cls: 'pickerfooterbtns',
                listeners : {
                    tap: function (button, e, options) {
                        this.up('calendarpicker').customBtns('CANCEL');
                    }
                }
            }
        ]};

        var getDts = Ext.create('widget.calendarpicker', {
            //     xtype: 'calendarpicker',
            hideTitleBar: true,
            itemId : 'calendar_lookup',
            selectMode: 'NONE',
            backMonths: 3,
            forwardMonths: 12,
            useIconsForExpCollapse: false,
            holidayDtArr: holidayDtArr,
            returnItem: returnItem,
            defaultCollapseLevel: 99,
            enableQuickDaySelection: true,
            height: '100%',
            width: '100%',
            includeCustomFooterItems: true,    
            customFooterItems: myCustomBtns,
            footerDock: 'top'
        });


        planner_cal.add(getDts);

        dateEx.setActiveItem(newcont);



    },

    onExample4_LookupSelected: function(calendarpicker, dateStr, date) {

        var dateEx = this.getDateexamples();
        var returnItem = dateEx.down('#example4');
        var plannerDetailText = dateEx.down('#plannerDetailText');

        if (!Ext.isEmpty(plannerDetailText)) {
            plannerDetailText.setHtml(dateStr);
        }

    },

    onExample4_LookupClosed: function(calendarpicker) {
        var dateEx = this.getDateexamples();

        var returnItem=calendarpicker.getReturnItem();

        // Restore title bar state
        var appTitle = dateEx.down('#appTitle');
        appTitle.setTitle(appTitle.origTitle);
        appTitle.setUi(appTitle.origUi);
        appTitle.setCls(appTitle.origCls);

        var planner_cal = dateEx.down('#planner_cal');
        var newcont = dateEx.down('#firstSet');
        dateEx.setActiveItem(newcont);
        planner_cal.removeAll(true, true);





    },

    onExample5_December: function(container) {
        var returnItem = this.getDateexamples().down('#example5');

        var myCategImg = '<img src="./resources/images/ribbon.png" class="christmas-categ-img">';

        var myCustomBtns = [ 
        {
            xtype: 'img',
            src: './resources/images/holly.png',
            cls: 'christmas-img'
        },     
        {
            xtype: 'label',
            html: 'Christmas Calendars',
            cls: 'christmas-label'
        }, 
        {    
            xtype: 'segmentedbutton',
            itemId : 'pickerfooterbtns',
            docked : 'right',
            items: [
            {
                xtype: 'button',
                text: 'RETURN',
                iconCls: '',
                cls: 'pickerfooterbtns',
                listeners : {
                    tap: function (button, e, options) {
                        this.up('calendarpicker').customBtns('CANCEL');
                    }
                }
            }
        ]}
        ];


        var myRend = {renderer_month: function (values)
            {return myCategImg+values.month + ' ' + values.year+myCategImg;},
            renderer_dates: function (fldName, values) {
                var elem=values[fldName];
                var hol = values['isHoliday_'+fldName];
                if (hol) {
                    elem = '<img src="./resources/images/christmas_tree.png" >';
                }
            return elem;},             
            cls_renderer_dates: function (fldName, values)
            {var cls="", dt, sel, hol, dis, par = this.scope.parent;
                dt = values['dt_'+fldName];
                hol = values['isHoliday_'+fldName];
                dis = values['isDisabled_'+fldName];

                if (values.rowType === 'H') {}  // do nothing for header rows
                else if (Ext.isEmpty(dt)) {} // do nothing for empty dates

                else if (hol) {
                return 'calendar-tree'; }     
                else {
                    sel = (par.getSelDtArr().indexOf(Ext.Date.format(dt, 'Y-m-d'))>-1);            
                    if (Ext.Date.format(dt, 'w')==='0' || Ext.Date.format(dt, 'w')==='6') {
                        cls = cls+' calendarpicker-weekend';
                    }   
                    if (hol){cls = cls+' calendarpicker-holiday';}
                    if (!Ext.isEmpty(this.scope.todayDt)){
                        if (this.scope.todayDt === Ext.Date.format(dt, 'Y-m-d')) {
                            cls = cls+' calendarpicker-today';
                        }
                    }     
                    if (dis){cls = cls+' calendarpicker-disabled';}
                    if (sel){cls = cls+' calendarpicker-selected';}
                }

                return ("calendarpicker-days" + cls);
            }};

            var myFilt = {
                enabled: true,
                displayNodesWithAllMembersFilteredAsLeafs: true,
                filterFn: function(rowObj) {return (rowObj.month === 'December');}
            };

            var getDts = Ext.create('widget.calendarpicker', {
                //     xtype: 'calendarpicker',
                title : 'Christmas Calendars',
                itemId : 'calendar_filter',
                customCls : ['calendarpicker-christmas'],
                selectMode: 'NONE',
                backMonths: 0,
                forwardMonths: 144,
                useIconsForExpCollapse: false,
                holidayDtArr: ['2013-12-25', '2014-12-25', '2015-12-25', '2016-12-26', '2017-12-25', '2018-12-25', '2019-12-25', '2020-12-25', '2021-12-24', '2022-12-26', '2023-12-25', '2024-12-25', '2025-12-25', '2026-12-25', '2027-12-25'],
                includeCustomFooterItems: true,
                returnItem: returnItem,
                defaultCollapseLevel: 99,
                height: '100%',
                width: '100%',
                customFooterItems: myCustomBtns,
                footerDock: 'top',
                hideExpandCollapseBtns: true,
                disableExpandCollapse: true,
                hideTitleBar: true,
                filter: myFilt,
                renderers: myRend

            });

            var overPnl = this.getOverlayPanel();
            overPnl.add(getDts);

            overPnl.showBy(container);
    },

    onExample5_DecemberClosed: function(calendarpicker) {
        var returnItem=calendarpicker.getReturnItem();

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    },

    onExample6_DayCount: function(container) {
        var returnItem = this.getDateexamples().down('#example6');

        var myCustomBtns = [     // NOTE:  Currently can't define as array if including Expand/Collapse All features  (in this case use Title instead of custom Label if needed)
        {
            xtype: 'label',
            html: 'Day Count Calendar',
            cls: 'daycount-label'
        }, 
        {    
            xtype: 'segmentedbutton',
            itemId : 'pickerfooterbtns',
            docked : 'right',
            items: [
            {
                xtype: 'button',
                text: 'RETURN',
                iconCls: '',
                cls: 'pickerfooterbtns',
                listeners : {
                    tap: function (button, e, options) {
                        this.up('calendarpicker').customBtns('CANCEL');
                    }
                }
            }
        ]}
        ];


        var myRend = {
            renderer_dates: function (fldName, values) {
                var elem=values[fldName];
                var dt = values['dt_'+fldName];
                var today= Ext.Date.clearTime(new Date(Date(Ext.Date.now())), true);
                var diff = Ext.Date.diff(today, dt, Ext.Date.DAY);
                if (diff>0) {
                    elem = elem+'<span class="daycount-inner"><br>'+diff.toString()+'</span>';
                }
                return elem;
            },
            cls_renderer_dates: function (fldName, values){
                var cls="", dt, sel, hol, dis, par = this.scope.parent;
                dt = values['dt_'+fldName];
                var today= Ext.Date.clearTime(new Date(Date(Ext.Date.now())), true);
                var diff = Ext.Date.diff(today, dt, Ext.Date.DAY);
                if (diff>0) {
                    cls = cls + ' daycount-outer';
                }          
                hol = values['isHoliday_'+fldName];
                dis = values['isDisabled_'+fldName];

                if (values.rowType === 'H') {
                cls = cls + ' calendarpicker-header';}  
                else if (Ext.isEmpty(dt)) {} // do nothing for empty dates
                else {
                    sel = (par.getSelDtArr().indexOf(Ext.Date.format(dt, 'Y-m-d'))>-1);
                    if (Ext.Date.format(dt, 'w')==='0' || Ext.Date.format(dt, 'w')==='6') {
                        cls = cls+' calendarpicker-weekend';
                    }   
                    if (hol){cls = cls+' calendarpicker-holiday';}
                    if (!Ext.isEmpty(this.scope.todayDt)){
                        if (this.scope.todayDt === Ext.Date.format(dt, 'Y-m-d')) {
                            cls = cls+' calendarpicker-today';
                        }
                    }     
                    if (dis){cls = cls+' calendarpicker-disabled';}
                    if (sel){cls = cls+' calendarpicker-selected';}
                }

                return ("calendarpicker-days" + cls);
            }};


            var getDts = Ext.create('widget.calendarpicker', {
                itemId : 'calendar_daycount',
                //   customCls : ['calendarpicker-daycount'],
                customCls : ['calendarpicker-ios'],

                selectMode: 'NONE',
                backMonths: 0,
                forwardMonths: 6,
                useIconsForExpCollapse: false,
                holidayDtArr: ['2013-12-25', '2014-12-25', '2015-12-25', '2016-12-26', '2017-12-25', '2018-12-25', '2019-12-25', '2020-12-25', '2021-12-24', '2022-12-26', '2023-12-25', '2024-12-25', '2025-12-25', '2026-12-25', '2027-12-25'],
                includeCustomFooterItems: true,
                returnItem: returnItem,
                defaultCollapseLevel: 99,
                itemHeight: 16,   // Set minimum value for weekday names row ... use css for other heights
                variableHeights: true,      
                height: '100%',
                width: '100%',
                customFooterItems: myCustomBtns,
                footerDock: 'top',
                hideExpandCollapseBtns: true,
                disableExpandCollapse: true,
                hideTitleBar: true,
                renderers: myRend

            });

            var overPnl = this.getOverlayPanel();
            overPnl.add(getDts);

            overPnl.showBy(container);
    },

    onExample6_DaycountClosed: function(calendarpicker) {
        var returnItem=calendarpicker.getReturnItem();

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    },

    onExample7_OptionDates: function(container) {
        var returnItem = this.getDateexamples().down('#example7');

        var customDateTypes = [
        {
            customType: 'holiday',
            customDescr: 'Holiday',
            useCustomDtArr: false,
            storeId: 'optionDates',
            priority: 4,
            disabled: false,
            cls: 'optionDates-holiday'
        },
        {
            customType: 'stopTrading',
            customDescr: 'Stop Trading',
            useCustomDtArr: false,
            storeId: 'optionDates',
            priority: 2,
            disabled: false,
            cls: 'optionDates-stopTrading'
        },
        {
            customType: 'optionsExpire',
            customDescr: 'Options Expire',
            useCustomDtArr: false,
            storeId: 'optionDates',
            priority: 1,
            disabled: false,
            cls: 'optionDates-optionsExpire'
        },
        {
            customType: 'quarterlyExpiration',
            customDescr: 'Quarterly Expiration',
            useCustomDtArr: false,
            storeId: 'optionDates',
            priority: 3,
            disabled: false,
            cls: 'optionDates-quarterlyExpiration'
        }
        ];


        var myCustomBtns = {    
            xtype: 'segmentedbutton',
            itemId : 'pickerfooterbtns',
            docked : 'right',
            items: [{
                xtype: 'button',
                text: 'RETURN',
                iconCls: '',
                cls: 'pickerfooterbtns',
                listeners : {
                    tap: function (button, e, options) {
                        this.up('calendarpicker').customBtns('CANCEL');
                    }
                }
            }]
        };

        var getDts = Ext.create('widget.calendarpicker', {
            itemId : 'calendar_optionDates',
            customCls : ['calendarpicker-optionDates'],
            title : 'Options Expiration Calendar',
            selectMode: 'NONE',
            backMonths: 0,
            forwardMonths: 15,
            useIconsForExpCollapse: false,
            holidayDtArr: [],
            returnItem: returnItem,
            defaultCollapseLevel: 99,
            height: '100%',
            width: '100%',
            includeCustomFooterItems: true,        
            customFooterItems: myCustomBtns,
            customDateTypes: customDateTypes,
            includeCustomDatesLegend: true

        });

        var overPnl = this.getOverlayPanel();
        overPnl.add(getDts);

        overPnl.showBy(container);
    },

    onExample7_OptionDatesClosed: function(calendarpicker) {
        var returnItem=calendarpicker.getReturnItem();

        var overPnl = this.getOverlayPanel();
        overPnl.removeAll(true, true);  // remove all items from DOM 
        overPnl.hide();
    }

});