/*
 * File: app/view/bigDataList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.bigDataList', {
    extend: 'Ext.Container',
    alias: 'widget.bigDataList',

    config: {
        itemId: 'bigDataList',
        layout: {
            type: 'hbox'
        },
        scrollable: {
            direction: 'horizontal',
            directionLock: true
        },
        items: [
            {
                xtype: 'touchtreegrid',
                store: 'BigDataStore',
                columns: [
                    {
                        header: 'Id',
                        dataIndex: 'employeeNo',
                        width: '70px',
                        style: 'text-align: center;',
                        sortable: true
                    },
                    {
                        header: 'Name',
                        dataIndex: 'surname',
                        width: '150px',
                        style: 'text-align: left; padding-left: 8px;',
                        renderer: 'this.fullName(values.forename, values.surname)',
                        sortable: true
                    }
                ],
                header: {
                    maxHeight: '59px',
                    minHeight: '59px'
                },
                variableHeights: false,
                itemHeight: 24,
                listItemId: 'bigDataListX',
                renderers: {
                    fullName: function(forename, surname)
                {return forename + ' ' + surname;}
                },
                headerTplOverride: '<div class="css-header-row ">\r\n<div class="touchtreegrid-header-cell " style="width:70px !important;text-align: center;" \r\n     dataindex="employeeNo">Id</div>\r\n<div class="touchtreegrid-header-cell " style="width:150px !important;text-align: left; padding-left: .5em;" \r\n     dataindex="surname">Name</div>\r\n</div>',
                simpleList: true,
                columnSorting: true,
                additionalListConfigs: {
                    grouped: true
                },
                infinite: true,
                linkedGridsParentItemId: 'bigDataList',
                linkedGridsArr: [
                    {
                        itemId: 'bigData'
                    }
                ],
                cls: [
                    'x-touchtreegrid-list',
                    'x-touchtreegrid-list-bigData'
                ],
                itemId: 'bigDataX',
                minWidth: '220px',
                style: 'border-right: 2px solid gray;',
                width: '220px'
            },
            {
                xtype: 'container',
                flex: 1,
                layout: {
                    type: 'hbox'
                },
                scrollable: {
                    direction: 'horizontal',
                    directionLock: true
                },
                items: [
                    {
                        xtype: 'touchtreegrid',
                        store: 'BigDataStore',
                        columns: [
                            {
                                header: 'Date of Birth',
                                dataIndex: 'dob',
                                width: '120px',
                                style: 'text-align: left;',
                                renderer: 'Ext.Date.format(values.dob, "m/d/Y")',
                                sortable: true
                            },
                            {
                                header: 'Join Date',
                                dataIndex: 'joinDate',
                                width: '120px',
                                style: 'text-align: left;',
                                renderer: 'Ext.Date.format(values.joinDate, "m/d/Y")',
                                sortable: true
                            },
                            {
                                header: 'Notice Period',
                                dataIndex: 'noticePeriod',
                                width: '120px',
                                style: 'text-align: left;',
                                sortable: true
                            },
                            {
                                header: 'Email address',
                                dataIndex: 'email',
                                width: '200px',
                                style: 'text-align: left;',
                                renderer: 'this.emailFormat(values.email)',
                                sortable: true
                            },
                            {
                                header: 'Illness',
                                dataIndex: 'sickDays',
                                width: '100px',
                                style: 'text-align: left;',
                                sortable: false
                            },
                            {
                                header: 'Holidays',
                                dataIndex: 'holidayDays',
                                width: '100px',
                                style: 'text-align: left;',
                                sortable: false
                            },
                            {
                                header: 'Holiday Allowance',
                                dataIndex: 'holidayAllowance',
                                width: '150px',
                                style: 'text-align: left;',
                                sortable: false
                            },
                            {
                                header: 'Rating',
                                dataIndex: 'rating',
                                width: '70px',
                                style: 'text-align: left;',
                                sortable: true
                            },
                            {
                                header: 'Salary',
                                dataIndex: 'salary',
                                width: '110px',
                                style: 'text-align: right; padding-right: 8px;',
                                sortable: true,
                                renderer: 'this.formatNumbers(values.salary,  0, \'$\')'
                            }
                        ],
                        header: {
                            maxHeight: '59px',
                            minHeight: '59px'
                        },
                        variableHeights: false,
                        itemHeight: 24,
                        listItemId: 'bigDataList',
                        renderers: {
                            emailFormat: function(email)
                        {return '<a href="mailto:' + email + '">' + email + '</a>';}
                        },
                        headerTplOverride: '<div class="css-header-row ">\r\n<div class="touchtreegrid-header-cell " style="width:120px !important;text-align: left;" dataindex="dob">Date of Birth</div>\r\n<div class="touchtreegrid-header-cell " style="width:120px !important;text-align: left;" dataindex="joinDate">Join Date</div>\r\n<div class="touchtreegrid-header-cell " style="width:120px !important;text-align: left;" dataindex="noticePeriod">Notice Period</div>\r\n<div class="touchtreegrid-header-cell " style="width:200px !important;text-align: left;" dataindex="email">Email address</div>\r\n\r\n<table cellpadding="0" cellspacing="0">\r\n<tr class="touchtreegrid-header-cell " style="line-height: 29px; border-bottom: 1px solid #c0c0c0; \r\n	border-right: 1px solid #c0c0c0; width:350px !important;text-align: center;"><td colspan="3">Absences</td></tr>\r\n<tr>\r\n<td class="touchtreegrid-header-cell " style="line-height: 30px; width:100px !important;text-align: left;">Illness</td>\r\n<td class="touchtreegrid-header-cell " style="line-height: 30px; width:100px !important;text-align: left;">Holidays</td>\r\n<td class="touchtreegrid-header-cell " style="line-height: 30px; width:150px !important;text-align: left;">Holiday Allowance</td>\r\n</tr>\r\n</table>\r\n\r\n<div class="touchtreegrid-header-cell " style="width:70px !important;text-align: left;" dataindex="rating">Rating</div>\r\n<div class="touchtreegrid-header-cell " style="width:110px !important;text-align: right;padding-right: 8px;" dataindex="salary">Salary</div>\r\n</div>',
                        simpleList: true,
                        columnSorting: true,
                        additionalListConfigs: {
                            grouped: true
                        },
                        infinite: true,
                        linkedGridsParentItemId: 'bigDataList',
                        linkedGridsArr: [
                            {
                                itemId: 'bigDataX'
                            }
                        ],
                        flex: 1,
                        cls: [
                            'x-touchtreegrid-list',
                            'x-touchtreegrid-list-bigData'
                        ],
                        itemId: 'bigData',
                        minWidth: '1200px',
                        width: '1200px'
                    }
                ]
            }
        ]
    }

});