{
    "xdsVersion": "2.2.2",
    "frameworkVersion": "touch22",
    "internals": {
        "type": "Ext.Container",
        "reference": {
            "name": "items",
            "type": "array"
        },
        "codeClass": null,
        "userConfig": {
            "store": "",
            "displayField": null,
            "listScrollable": [
                "true"
            ],
            "headerItemTpl": null,
            "contentItemTpl": "",
            "useAnimation": null,
            "list": [
                "{}"
            ],
            "headerItemOuter": null,
            "headerItemData": null,
            "disableSelection": true,
            "listStyle": null,
            "onItemDisclosure": false,
            "columns": [
                "[]"
            ],
            "header": [
                "{\r",
                "            xtype: 'toolbar',\r",
                "            docked: 'top',\r",
                "            cls: 'touchtreegrid-header',\r",
                "            maxHeight: '1.8em',\r",
                "            minHeight: '1.8em'\r",
                "        }"
            ],
            "headerTpl": "",
            "variableHeights": true,
            "itemHeight": 47,
            "disclosureProperty": "disclose",
            "listItemId": "touchtreegridlist",
            "categItemTpl": "",
            "footer": [
                "{\r",
                "            xtype: 'toolbar',\r",
                "            docked: 'bottom',\r",
                "            ui     : 'light',\r",
                "            cls: 'touchtreegrid-footer'\r",
                "        }"
            ],
            "includeFooter": true,
            "plugins": null,
            "listPlugins": [
                "{}"
            ],
            "categIndentPct": "3",
            "colNumberToTruncateForIndents": 1,
            "includeFooterLevels": true,
            "categDepthColors": false,
            "categDepthColorsArr": [
                "[\r",
                "'#a6a6a6',\r",
                "'#dddddd',\r",
                "'white'\r",
                "]"
            ],
            "customExpCollapseEvent": "",
            "renderers": [
                "{}"
            ],
            "categDepthColorButtons": true,
            "pressedBtnCls": null,
            "useCustomPressedBtnCls": null,
            "categItemTplOverride": "",
            "contentItemTplOverride": "",
            "headerTplOverride": "",
            "includeHeader": true,
            "applyDefaultCollapseLevel": true,
            "defaultCollapseLevel": 99,
            "landscapeIcon": "",
            "helpHtml": "",
            "pressedCls": "touchtreegrid-item-pressed",
            "simpleList": false,
            "columnSorting": false,
            "styleContentRow": "display: -webkit-box; -webkit-box-orient: horizontal;",
            "styleCategRow": "display: -webkit-box; -webkit-box-orient: horizontal;",
            "styleHeaderRow": "display: -webkit-box; -webkit-box-orient: horizontal;",
            "singleExpand": false,
            "additionalListConfigs": [
                "{}"
            ],
            "selectedCls": "touchtreegrid-item-selected",
            "mode": "SINGLE",
            "useSimpleItems": true,
            "infinite": true,
            "arrowPctWidth": "4",
            "customColumnSortEvent": "",
            "disableExpandCollapse": false,
            "categColumns": [
                "[]"
            ],
            "categCssArr": [
                "[]"
            ],
            "cls": [
                "x-touchtreegrid-list"
            ],
            "designer|userClassName": "TouchTreeGrid",
            "designer|userAlias": "touchtreegrid",
            "layout": "vbox",
            "scrollable": null
        },
        "configAlternates": {
            "listScrollable": "object",
            "defaultExpanded": "boolean",
            "useAnimation": "boolean",
            "disableSelection": "boolean",
            "listStyle": "object",
            "onItemDisclosure": "boolean",
            "headerItemData": "array",
            "columns": "array",
            "header": "object",
            "variableHeights": "boolean",
            "itemHeight": "number",
            "footer": "object",
            "includeFooter": "boolean",
            "list": "object",
            "plugins": "object",
            "listPlugins": "object",
            "colNumberToTruncateForIndents": "number",
            "includeFooterLevels": "boolean",
            "categDepthColors": "boolean",
            "categDepthColorsArr": "array",
            "renderers": "object",
            "categDepthColorButtons": "boolean",
            "useCustomPressedBtnCls": "boolean",
            "includeHeader": "boolean",
            "autoApplyCollapseConfig": "boolean",
            "applyDefaultCollapseLevel": "boolean",
            "defaultCollapseLevel": "number",
            "simpleList": "boolean",
            "headerSorting": "boolean",
            "columnSorting": "boolean",
            "singleExpand": "boolean",
            "additionalListConfigs": "object",
            "useSimpleItems": "boolean",
            "infinite": "boolean",
            "scrollable": "object",
            "disableExpandCollapse": "boolean",
            "categColumns": "array",
            "categCssArr": "array"
        },
        "customConfigs": [
            {
                "group": "(Custom Properties)",
                "name": "store",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "displayField",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "listScrollable",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "headerItemTpl",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "contentItemTpl",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "useAnimation",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "list",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "headerItemOuter",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "headerItemInner",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "headerItemData",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "disableSelection",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "listStyle",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "onItemDisclosure",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "columns",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "header",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "headerTpl",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "variableHeights",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "itemHeight",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "disclosureProperty",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "listItemId",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categItemTpl",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "footer",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "includeFooter",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "plugins",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "listPlugins",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categIndentPct",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "colNumberToTruncateForIndents",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "includeFooterLevels",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categDepthColors",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categDepthColorsArr",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "customExpCollapseEvent",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "renderers",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categDepthColorButtons",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "pressedBtnCls",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "useCustomPressedBtnCls",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categItemTplOverride",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "contentItemTplOverride",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "headerTplOverride",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "includeHeader",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "applyDefaultCollapseLevel",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "defaultCollapseLevel",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "landscapeIcon",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "helpHtml",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "pressedCls",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "simpleList",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "columnSorting",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "styleContentRow",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "styleCategRow",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "styleHeaderRow",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "singleExpand",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "additionalListConfigs",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "selectedCls",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "mode",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "useSimpleItems",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "infinite",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "arrowPctWidth",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "customColumnSortEvent",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "disableExpandCollapse",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categColumns",
                "type": "string"
            },
            {
                "group": "(Custom Properties)",
                "name": "categCssArr",
                "type": "string"
            }
        ],
        "cn": [
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "initialize",
                    "designer|params": [
                        "config"
                    ],
                    "implHandler": [
                        "var me = this;\r",
                        "\r",
                        "me.callParent(arguments);\r",
                        "\r",
                        "this.doRefreshList();\r",
                        "\r",
                        "\r",
                        ""
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "updateColumns",
                    "implHandler": [
                        "// UPDATE functions on config items execute prior to INITIALIZE (and before UPDATESTORE) so \r",
                        "// insert logic here to build ItemTpl components\r",
                        "// NOTE:  Columns updated in this Class as [initialize] to force execution of this function.\r",
                        "\r",
                        "var me = this, myWidth, myWidthVal;\r",
                        "\r",
                        "var simpleList = me.getSimpleList();\r",
                        "\r",
                        "// Proceed to build TPL for header row\r",
                        "var styleStr = '', rendStr='', cssStr='';\r",
                        "var categ = me.getCategItemTplOverride();\r",
                        "var indent = me.getCategIndentPct().toString().replace(\"%\", \"\"); // % of window to indent per level (starting at 0% ... default =3%)\r",
                        "var arrowWid = me.getArrowPctWidth().toString().replace(\"%\", \"\"); // allow control over percent screen width that category arrow consumes (def = 4%)\r",
                        "\r",
                        "\r",
                        "var categStyle = Ext.isEmpty(me.getStyleCategRow()) ? '' : ' style=\"' + me.getStyleCategRow() + '\"';\r",
                        "var contentStyle = Ext.isEmpty(me.getStyleContentRow()) ? '' : ' style=\"' + me.getStyleContentRow() + '\"';\r",
                        "\r",
                        "var indentCol = me.getColNumberToTruncateForIndents()-1; // This column width value will be truncated to account for indent\r",
                        "// Subtract 1 from column number to array index # applied below.\r",
                        "// Width expected to be in pct format as last '%' character will be stripped for computation : '25%'\r",
                        "\r",
                        "var data = me.getColumns(); // single dimention array of objects defining each column\r",
                        "var categData = me.getCategColumns(); // optional multi-dimension array of objects of category columns defs by level\r",
                        "\r",
                        "if (this.isObjectEmpty(data)) {  \r",
                        "    // Initialize column data for scenario where column array updated within controller after component initialization\r",
                        "    data ={header: '', dataIndex: '', width: '', style: '', categStyle: '', headerStyle: ''};\r",
                        "}\r",
                        "\r",
                        "var shellArr=[], i, k, categArr=[],\r",
                        "    prefixArr = \r",
                        "    [\r",
                        "    '<div' + categStyle + '>',\r",
                        "    '<p align=\"left\" style=\"width:{[(values.depth-1)*'+indent+']}%;\"</p>',    // 3% per depth starting at 0% \r",
                        "    '<p align=\"left\" style=\"width:'+arrowWid+'%;min-width:'+arrowWid+'%;max-width:'+arrowWid+'%;white-space: nowrap;overflow:hidden;text-overflow:ellipsis;\">', \r",
                        "    '<span class=\"touchtreegrid-details-img ',\r",
                        "    '<tpl if=\"this.isExpanded(values)\">',   \r",
                        "    'touchtreegrid-details-img-open\" </span></p>',\r",
                        "    '<tpl else>',  \r",
                        "    'touchtreegrid-details-img-close\" </span></p>',\r",
                        "    '</tpl>'\r",
                        "    ];\r",
                        "\r",
                        "if (categ==='' && !simpleList && Ext.isEmpty(categData)) {   \r",
                        "    // Process category row TPL (same TPL for all category rows defined via Columns array)\r",
                        "\r",
                        "    shellArr.push(prefixArr.join(''));\r",
                        "    for (i=0; i<data.length; i++) {\r",
                        "\r",
                        "        // Use categStyle if exists, else apply detail row style to category row\r",
                        "        if (!Ext.isEmpty(data[i].categStyle) && data[i].categStyle > '') {styleStr = data[i].categStyle;}\r",
                        "        else if (!Ext.isEmpty(data[i].style)) {styleStr = data[i].style;}\r",
                        "        else {styleStr = '';}\r",
                        "\r",
                        "        // Use categCss if exists, else apply detail row css to category row (if defined)\r",
                        "        if (!Ext.isEmpty(data[i].categCss) && data[i].categCss > '') {cssStr = data[i].categCss;}\r",
                        "        else if (!Ext.isEmpty(data[i].css)) {cssStr = data[i].css;}\r",
                        "        else {cssStr = '';}\r",
                        "\r",
                        "        // Substitute user-defined renderer string from Columns array if defined\r",
                        "        rendStr = (Ext.isEmpty(data[i].renderer) ? (Ext.isEmpty(data[i].dataIndex) ? '' : data[i].dataIndex) : '[' + data[i].renderer + ']');\r",
                        "\r",
                        "        if (i===indentCol) {    \r",
                        "            // Subtract percentage width based on level          \r",
                        "            shellArr.push('<p class=\"touchtreegrid-list-categ-cell ' + cssStr + '\" style=\"' +\r",
                        "            'min-width:{[' + data[i].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            'max-width:{[' + data[i].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            'width:{[' + data[i].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            styleStr + '\" >{' + rendStr + '}</p>');                       \r",
                        "        } else {           \r",
                        "            shellArr.push('<p class=\"touchtreegrid-list-categ-cell \" style=\"' +\r",
                        "            'min-width:' + data[i].width + ' !important;' + \r",
                        "            'max-width:' + data[i].width + ' !important;' + \r",
                        "            'width:' + data[i].width + ' !important;' + \r",
                        "            styleStr + '\" >{' + rendStr + '}</p>');\r",
                        "        }  \r",
                        "    }\r",
                        "\r",
                        "    shellArr.push('</div>');  \r",
                        "    categ=shellArr.join('');\r",
                        "    me.setCategItemTpl(categ);\r",
                        "}\r",
                        "else if (categ==='' && !simpleList && !Ext.isEmpty(categData)) {\r",
                        "    // Process category row TPL as defined in categColumns.  \r",
                        "\r",
                        "    shellArr = []; \r",
                        "    shellArr.push(prefixArr.join(''));  // Initialize with arrow and row style definitions\r",
                        "\r",
                        "    for (i=0; i<categData.length; i++) {  // loop for each object defined in current sub-array\r",
                        "\r",
                        "        // Use categStyle if exists, else apply detail row style to category row\r",
                        "        if (!Ext.isEmpty(categData[i].categStyle) && categData[i].categStyle > '') {styleStr = categData[i].categStyle;}\r",
                        "        else if (!Ext.isEmpty(categData[i].style)) {styleStr = categData[i].style;}\r",
                        "        else {styleStr = '';}\r",
                        "\r",
                        "        // Use categCss if exists, else apply detail row css to category row (if defined)\r",
                        "        if (!Ext.isEmpty(categData[i].categCss) && categData[i].categCss > '') {cssStr = categData[i].categCss;}\r",
                        "        else if (!Ext.isEmpty(categData[i].css)) {cssStr = categData[i].css;}\r",
                        "        else {cssStr = '';}\r",
                        "\r",
                        "        // Substitute user-defined renderer string from Columns array if defined\r",
                        "        rendStr = ((!categData[i].renderer) ? (Ext.isEmpty(categData[i].dataIndex) ? '' : categData[i].dataIndex) : '[' + categData[i].renderer + ']');\r",
                        "\r",
                        "        if (i===indentCol) {     \r",
                        "            // Subtract percentage width based on level             \r",
                        "            shellArr.push('<p class=\"touchtreegrid-list-categ-cell ' + cssStr + '\" style=\"' +\r",
                        "            'min-width:{[' + categData[i].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            'max-width:{[' + categData[i].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            'width:{[' + categData[i].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            styleStr + '\" >{' + rendStr + '}</p>');                       \r",
                        "        } else {           \r",
                        "            shellArr.push('<p class=\"touchtreegrid-list-categ-cell ' + cssStr + '\" style=\"' +\r",
                        "            'min-width:' + data[i].width + ' !important;' + \r",
                        "            'max-width:' + data[i].width + ' !important;' + \r",
                        "            'width:' + data[i].width + ' !important;' + \r",
                        "            styleStr + '\" >{' + rendStr + '}</p>');\r",
                        "        }  \r",
                        "    }\r",
                        "\r",
                        "    shellArr.push('</div>');  \r",
                        "    categArr=shellArr.join('');\r",
                        "\r",
                        "    me.setCategItemTpl(categArr);  \r",
                        "\r",
                        "}\r",
                        "else {me.setCategItemTpl(categ);}  // simply update with TPL provided in CategItemTplOverride config (ignored for simpleList=true)\r",
                        "\r",
                        "\r",
                        "\r",
                        "var detail = me.getContentItemTplOverride();\r",
                        "var detailArr, j;\r",
                        "if (detail==='' && !simpleList) {\r",
                        "    detailArr = [\r",
                        "    '<div' + contentStyle + '>',\r",
                        "    '<p align=\"left\" style=\"width:{[(values.depth-1)*'+indent+']}%;\"</p>',    // 3% per depth starting at 0%         \r",
                        "    '<p align=\"left\" style=\"width:'+arrowWid+'%;min-width:'+arrowWid+'%;max-width:'+arrowWid+'%;white-space: nowrap;overflow:hidden;text-overflow:ellipsis;\">&nbsp;</p>'\r",
                        "    ];\r",
                        "\r",
                        "    for (j=0; j<data.length; j++) {\r",
                        "\r",
                        "        // Substitute user-defined renderer string from Columns array if defined\r",
                        "        rendStr = ((!data[j].renderer) ? (Ext.isEmpty(data[j].dataIndex) ? '' : data[j].dataIndex) : '[' + data[j].renderer + ']');\r",
                        "\r",
                        "        cssStr = (Ext.isEmpty(data[j].css)) ? '' : data[j].css;        \r",
                        "\r",
                        "        if (j===indentCol) {     \r",
                        "            // Subtract percentage width based on level\r",
                        "            detailArr.push('<p class=\"touchtreegrid-list-content-cell ' + cssStr + '\" style=\"' +\r",
                        "            'min-width:{[' + data[j].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            'max-width:{[' + data[j].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            'width:{[' + data[j].width.replace(\"%\", \"\") + '-((values.depth-1)*'+indent+')]}% !important;' + \r",
                        "            (Ext.isEmpty(data[j].style) ? '' : data[j].style) + '\" ' +\r",
                        "            '>{' + rendStr + '}</p>');                  \r",
                        "        } else {           \r",
                        "            detailArr.push('<p class=\"touchtreegrid-list-content-cell \" style=\"' +\r",
                        "            'min-width:' + data[j].width + ' !important;' + \r",
                        "            'max-width:' + data[j].width + ' !important;' + \r",
                        "            'width:' + data[j].width + ' !important;' + \r",
                        "            (Ext.isEmpty(data[j].style) ? '' : data[j].style) + '\" ' +\r",
                        "            '>{' + rendStr + '}</p>');\r",
                        "        }          \r",
                        "\r",
                        "    }\r",
                        "\r",
                        "    detailArr.push('</div>');  \r",
                        "    detail=detailArr.join('');    \r",
                        "}   \r",
                        "if (detail==='' && simpleList) {\r",
                        "    detailArr = [\r",
                        "    // webkit-box handled by  \"display : inline-block;\" in TouchTreeGrid.css \r",
                        "    //   '<div style=\"display: -webkit-box;-webkit-box-orient: horizontal;\">',\r",
                        "    ];\r",
                        "\r",
                        "    for (j=0; j<data.length; j++) {\r",
                        "\r",
                        "        // Substitute user-defined renderer string from Columns array if defined\r",
                        "        rendStr = ((!data[j].renderer) ? data[j].dataIndex : '[' + data[j].renderer + ']');\r",
                        "\r",
                        "        cssStr = (Ext.isEmpty(data[j].css)) ? '' : data[j].css;        \r",
                        "\r",
                        "        detailArr.push('<p class=\"touchtreegrid-simplelist-cell ' + cssStr + '\" style=\"' +\r",
                        "        'min-width:' + data[j].width + ' !important;' + \r",
                        "        'max-width:' + data[j].width + ' !important;' + \r",
                        "        'width:' + data[j].width + ' !important;' + \r",
                        "        (Ext.isEmpty(data[j].style) ? '' : data[j].style) + '\" ' +\r",
                        "        '>{' + rendStr + '}</p>');\r",
                        "\r",
                        "    }\r",
                        "\r",
                        "    //   detailArr.push('</div>');  \r",
                        "    detail=detailArr.join('');    \r",
                        "}   \r",
                        "var content = me.setContentItemTpl(detail);    \r",
                        ""
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "updateStore",
                    "designer|params": [
                        "newStore",
                        "oldStore"
                    ],
                    "implHandler": [
                        "var me = this;\r",
                        "\r",
                        "var list = me.getList();\r",
                        "var disableSel = me.getDisableSelection();\r",
                        "var pressedCls = (disableSel ? '' : me.getPressedCls());  // Don't apply pressing class if selection disabled\r",
                        "var selectedCls = me.getSelectedCls();\r",
                        "var mode = me.getMode();\r",
                        "var disclose = me.getOnItemDisclosure();\r",
                        "var discloseProp = me.getDisclosureProperty();\r",
                        "var itemHeight = me.getItemHeight();\r",
                        "var variableHeights = me.getVariableHeights();\r",
                        "var infinite = me.getInfinite();\r",
                        "var useSimpleItems = me.getUseSimpleItems();\r",
                        "\r",
                        "if (this.isObjectEmpty(list)) {\r",
                        "\r",
                        "    list = Ext.create('Ext.dataview.List', {   \r",
                        "        disableSelection: disableSel,\r",
                        "        onItemDisclosure : disclose,\r",
                        "        disclosureProperty : discloseProp,  // 'disclose' for all rows (default), 'leaf' for leafs only\r",
                        "        itemHeight: itemHeight,\r",
                        "        variableHeights: variableHeights,\r",
                        "        store: newStore,\r",
                        "        masked: false,\r",
                        "        itemCls: 'x-touchtreegrid-item',\r",
                        "        pressedCls : pressedCls,\r",
                        "        selectedCls : selectedCls,\r",
                        "        useSimpleItems: useSimpleItems,\r",
                        "        infinite: infinite,\r",
                        "        mode: mode,\r",
                        "        height: '100%'\r",
                        "    });\r",
                        "\r",
                        "    // Support application of width, minWidth, height, minHeight overrides from linked instance for Horizontal scrolling\r",
                        "    var height = me.getHeight(); // Horiz scrolling doesn't work with 100% for some reason so any pixel setting\r",
                        "    // larger than expected works.  Example: 1000 (not sure why)\r",
                        "    if (!Ext.isEmpty(height)) {list.setHeight(height);}\r",
                        "    var minHeight = me.getMinHeight();\r",
                        "    if (!Ext.isEmpty(minHeight)) {list.setMinHeight(minHeight);}\r",
                        "    var width = me.getWidth();\r",
                        "    if (!Ext.isEmpty(width)) {list.setWidth(width);}\r",
                        "    var minWidth = me.getMinWidth();\r",
                        "    if (!Ext.isEmpty(minWidth)) {list.setMinWidth(minWidth);}                                                              \r",
                        "\r",
                        "    list.on('itemtap', me.onItemTap, me);\r",
                        "\r",
                        "    var plugins = me.getListPlugins();\r",
                        "    if (!this.isObjectEmpty(plugins)) {\r",
                        "        list.setPlugins(plugins);\r",
                        "    }\r",
                        "\r",
                        "    me.setList(list);\r",
                        "\r",
                        "    if (!me.getListScrollable()) {\r",
                        "        list.setScrollable({disabled: true});  // false doesn't seem to work\r",
                        "    } else {\r",
                        "        list.setScrollable(me.getListScrollable());\r",
                        "    }\r",
                        "\r",
                        "    var listItemId = me.getListItemId();\r",
                        "    if (listItemId !== '') {\r",
                        "        list.setItemId(listItemId);\r",
                        "    }\r",
                        "\r",
                        "    // Update list with any additional configs defined in user-defined additionalListConfigs object\r",
                        "    // (this allows all configs supported by Ext.dataview.List component to be applied to TouchTreeGrid list\r",
                        "    // Note:  any duplicated configs already supported by TouchTreeGrid will overwrite those and could have \r",
                        "    //        unexpected behaviour !!\r",
                        "    var addlConfigs = me.getAdditionalListConfigs();\r",
                        "    if (!me.isObjectEmpty(addlConfigs)) {\r",
                        "        for (cfg in addlConfigs) {\r",
                        "            list.config[cfg] = addlConfigs[cfg];\r",
                        "            list['_'+cfg] = addlConfigs[cfg];\r",
                        "        }\r",
                        "    }\r",
                        "\r",
                        "    me.add(list);\r",
                        "}\r",
                        "else {\r",
                        "    list.setStore(newStore);\r",
                        "}    \r",
                        "\r",
                        "\r",
                        "\r",
                        "\r",
                        "\r",
                        ""
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "onItemTap",
                    "designer|params": [
                        "list",
                        "index",
                        "target",
                        "record",
                        "e"
                    ],
                    "implHandler": [
                        "/**\r",
                        "* Called when an list item has been tapped\r",
                        "* @param list: {Ext.List}  The subList the item is on\r",
                        "* @param index: {Number} The id of the item tapped\r",
                        "* @param target: {Ext.Element} The list item tapped\r",
                        "* @param record: {Ext.data.Record} The record whichw as tapped\r",
                        "* @param e: {Ext.event.Event} The event\r",
                        "*/\r",
                        "\r",
                        "var store = list.getStore(),\r",
                        "    node = store.getAt(index),\r",
                        "    disabledExpColl = this.getDisableExpandCollapse();\r",
                        "\r",
                        "if (this.getOnItemDisclosure() && !Ext.isEmpty(e.getTarget('div.x-list-disclosure'))) {\r",
                        "    return;  // Ref:  http://www.sencha.com/forum/showthread.php?261518-List-onItemDisclosure-ST-2.2\r",
                        "}\r",
                        "\r",
                        "if (this.getSimpleList() || node.isLeaf()) {\r",
                        "    this.fireEvent('leafItemTap', this, list, index, target, record, e);\r",
                        "\r",
                        "} \r",
                        "else if (this.getSingleExpand() && !node.isExpanded()) {\r",
                        "    // If node collapsed, then expand this one and collapse all sibling nodes\r",
                        "    this.fireEvent('nodeItemTap', this, list, index, target, record, e);\r",
                        "\r",
                        "    if (!disabledExpColl) {\r",
                        "        node.expand(false);\r",
                        "        var parent = node.parentNode;\r",
                        "        var children = parent.childNodes;\r",
                        "        for (var i=0; i<children.length; i++) {\r",
                        "            if (children[i] !== node && children[i].isExpanded()) {\r",
                        "                children[i].collapse();\r",
                        "            }\r",
                        "        }\r",
                        "    }\r",
                        "}\r",
                        "else {\r",
                        "    this.fireEvent('nodeItemTap', this, list, index, target, record, e);  \r",
                        "\r",
                        "    if (!disabledExpColl && node.isExpandable()) {\r",
                        "        var xPosition = list.getScrollable().getScroller().position.x;\r",
                        "        var yPosition = list.getScrollable().getScroller().position.y;\r",
                        "\r",
                        "        if (node.isExpanded()) {\r",
                        "            node.collapse();\r",
                        "        } else {\r",
                        "            node.expand(false); \r",
                        "        }\r",
                        "\r",
                        "        list.getScrollable().getScroller().scrollTo(xPosition, yPosition, {duration: 0});\r",
                        "    }\r",
                        "\r",
                        "}"
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "applyHeader",
                    "designer|params": [
                        "config"
                    ],
                    "implHandler": [
                        "if (this.getIncludeHeader()) {\r",
                        "    Ext.apply(config, {\r",
                        "        docked : 'top',\r",
                        "        cls    : 'touchtreegrid-header',\r",
                        "        itemId : 'touchtreegridheader'\r",
                        "    });\r",
                        "\r",
                        "    return Ext.factory(config, Ext.Toolbar);\r",
                        "}    "
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "updateHeader",
                    "designer|params": [
                        "header"
                    ],
                    "implHandler": [
                        "var me = this;\r",
                        "if (me.getIncludeHeader()) {\r",
                        "    me.insert(0, header);\r",
                        "\r",
                        "    if (this.getColumnSorting()) {  // add tap event listener to header toolbar\r",
                        "        header.element.on('tap', me[\"handleColumnSort\"], me, {});\r",
                        "    }\r",
                        "}    "
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "applyFooter",
                    "designer|params": [
                        "config"
                    ],
                    "implHandler": [
                        "var me = this;\r",
                        "\r",
                        "var img = me.getLandscapeIcon();\r",
                        "\r",
                        "if (this.getIncludeFooter() && !this.getSimpleList()) {\r",
                        "    Ext.apply(config, {\r",
                        "        docked : 'bottom',\r",
                        "        cls    : 'touchtreegrid-footer',\r",
                        "        itemId : 'touchtreegridbuttons',\r",
                        "\r",
                        "        items: [\r",
                        "        {\r",
                        "            xtype: 'label',\r",
                        "            docked: 'right',\r",
                        "            html: '',\r",
                        "            itemId: 'touchtreegridlabel',\r",
                        "            cls  : 'touchtreegrid-landscape-label',                       \r",
                        "            style: 'color : white'\r",
                        "        },            \r",
                        "        {\r",
                        "            xtype: 'image',\r",
                        "            docked: 'right',\r",
                        "            hidden: true,\r",
                        "            itemId: 'touchtreegridicon',\r",
                        "            cls: 'touchtreegrid-landscape-icon',\r",
                        "            src: img\r",
                        "        },\r",
                        "        {\r",
                        "            xtype: 'segmentedbutton',\r",
                        "            itemId : 'touchtreegridsegmentedbuttons',\r",
                        "            items: [\r",
                        "            {\r",
                        "                xtype: 'button',\r",
                        "                itemId: 'touchtreegridexpand',\r",
                        "                cls  : 'touchtreegrid-expand-collapse-buttons',\r",
                        "                text: 'Expand',\r",
                        "                listeners : {\r",
                        "                    tap: function (button, e, options) {\r",
                        "                        me.doExpandDepth(99);\r",
                        "                    }\r",
                        "                }\r",
                        "            },\r",
                        "            {\r",
                        "                xtype: 'button',\r",
                        "                itemId: 'touchtreegridcollapse',\r",
                        "                cls  : 'touchtreegrid-expand-collapse-buttons',\r",
                        "                text: 'Collapse',\r",
                        "                listeners : {\r",
                        "                    tap: function (button, e, options) {\r",
                        "                        me.doExpandDepth(0);\r",
                        "                    }\r",
                        "                }\r",
                        "            }\r",
                        "            ]\r",
                        "\r",
                        "        }]\r",
                        "    });\r",
                        "\r",
                        "\r",
                        "\r",
                        "\r",
                        "    return Ext.factory(config, Ext.Toolbar);\r",
                        "}"
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "doExpandDepth",
                    "designer|params": [
                        "depth",
                        "btn"
                    ],
                    "implHandler": [
                        "var list = this.getList(),\r",
                        "    store = list.getStore();\r",
                        "\r",
                        "/* Unpress Expand/Collapse buttons in event they were pressed */\r",
                        "if (!Ext.isEmpty(btn)) {\r",
                        "    var btns  = this.down('#touchtreegridsegmentedbuttons');\r",
                        "    btns.setPressedButtons([]);\r",
                        "}\r",
                        "\r",
                        "// Fire custom event for expand/collapse if specified\r",
                        "var customEvent = this.getCustomExpCollapseEvent();\r",
                        "if (customEvent !== '') {\r",
                        "    this.fireEvent(customEvent, {collapseLevel: depth, list: list, gridcont: this});\r",
                        "    return;\r",
                        "}\r",
                        "\r",
                        "store.each(function(item, index, list) {item.collapse(true);});\r",
                        "\r",
                        "function expandDepth(node) {\r",
                        "    if (!node.isLeaf() && node.data.depth <depth) {\r",
                        "        node.expand(false);\r",
                        "\r",
                        "        node.childNodes.forEach(expandDepth, this);\r",
                        "    }\r",
                        "}\r",
                        "store.each(expandDepth, this);\r",
                        "\r",
                        ""
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "doRefreshList",
                    "designer|params": [
                        "skipApplyDefaultCollapseLevel"
                    ],
                    "implHandler": [
                        "// Refreshes TPL in grid and in Header\r",
                        "\r",
                        "var me = this;\r",
                        "\r",
                        "var simpleList = me.getSimpleList();\r",
                        "\r",
                        "var list = me.getList();\r",
                        "var disclose = me.getOnItemDisclosure();\r",
                        "var colorArr = me.getCategDepthColorsArr();\r",
                        "var categCssArr = me.getCategCssArr();\r",
                        "var colorDepth = me.getCategDepthColors();\r",
                        "var colorDepthButtons = me.getCategDepthColorButtons();\r",
                        "var arrowWid = me.getArrowPctWidth(); // allow control over percent screen width that category arrow consumes (def = 4%)\r",
                        "\r",
                        "var itemTpl;\r",
                        "\r",
                        "// Customize TPL to change colors by category depth as defined in colorArr\r",
                        "var colorStyle = (colorDepth ? ' style=\"background-color: {[this.depthColor(values)]} !important;\"' : '');\r",
                        "var categCss = '{[this.depthCategCss(values)]}';\r",
                        "\r",
                        "var tpl;\r",
                        "if (!simpleList) {\r",
                        "\r",
                        "    tpl = [\r",
                        "    '<tpl if=\"leaf\">',\r",
                        "    '<div class=\"touchtreegrid-list-content\">',\r",
                        "    me.getContentItemTpl(),\r",
                        "    '</div>', \r",
                        "    '<tpl else>',\r",
                        "    '<div class=\"' + categCss + '\" ' + colorStyle + '> ',\r",
                        "    me.getCategItemTpl(),\r",
                        "    '</div>',  \r",
                        "    '</tpl>'\r",
                        "    ].join('');\r",
                        "\r",
                        "} else {\r",
                        "    tpl = [\r",
                        "    //    '<div class=\"touchtreegrid-list-content\">',\r",
                        "    me.getContentItemTpl()\r",
                        "    //   '</div>'\r",
                        "    ].join('');\r",
                        "}\r",
                        "\r",
                        "var renderers = {};\r",
                        "renderers.scope = me;\r",
                        "renderers.isExpanded = function(values) {return values.expanded;};\r",
                        "renderers.depthColor = function(values) {return (!colorArr[values.depth-1] ? 'white' : colorArr[values.depth-1]);};\r",
                        "renderers.depthCategCss = function(values) {return (!categCssArr[values.depth-1] ? ' touchtreegrid-list-categ' : ' '+categCssArr[values.depth-1]);};\r",
                        "renderers.formatNumbers = function(n, decPlaces, prefix, thouSeparator, decSeparator) {return me.formatNumbers(n, decPlaces, prefix, thouSeparator, decSeparator);};\r",
                        "\r",
                        "var customRenderers = me.getRenderers();\r",
                        "for (var prop in customRenderers) {\r",
                        "    renderers[prop] = customRenderers[prop];\r",
                        "}\r",
                        "\r",
                        "itemTpl = Ext.create('Ext.XTemplate', tpl, renderers);\r",
                        "\r",
                        "itemTpl.compile();\r",
                        "\r",
                        "list.setItemTpl(itemTpl);\r",
                        "\r",
                        "if (simpleList) list.refresh();\r",
                        "\r",
                        "/* Build Header TPL */\r",
                        "var header = me.getHeader();\r",
                        "var data = me.getColumns();\r",
                        "\r",
                        "var styleStr='', cssStr='';\r",
                        "var headerStyle = Ext.isEmpty(me.getStyleHeaderRow()) ? '' : ' style=\"' + me.getStyleHeaderRow() + '\"';\r",
                        "\r",
                        "var headerTpl = me.getHeaderTplOverride();\r",
                        "if (headerTpl==='') {\r",
                        "\r",
                        "    var headerTplArr = [\r",
                        "    '<div' + headerStyle + '>'\r",
                        "    ];\r",
                        "    if (!simpleList) {\r",
                        "        // Include spacer width for category arrow\r",
                        "        headerTplArr.push('<p align=\"left\" style=\"width:'+arrowWid+'%;min-width:'+arrowWid+'%;max-width:'+arrowWid+\r",
                        "        '%;white-space: nowrap;overflow:hidden;text-overflow:ellipsis;\">&nbsp;</p>');\r",
                        "    }\r",
                        "\r",
                        "    for (var j=0; j<data.length; j++) {\r",
                        "\r",
                        "        // Use headerStyle if exists, else apply detail row style to category row\r",
                        "        if (data[j].headerStyle && data[j].headerStyle > '') {styleStr = data[j].headerStyle;}\r",
                        "        else if (data[j].style) {styleStr = data[j].style;}\r",
                        "        else {styleStr = '';}        \r",
                        "\r",
                        "        // Use headerCss if exists, else apply detail row css to header row (if defined)\r",
                        "        if (!Ext.isEmpty(data[j].headerCss) && data[j].headerCss > '') {cssStr = data[j].headerCss;}\r",
                        "        else if (!Ext.isEmpty(data[j].css)) {cssStr = data[j].css;}\r",
                        "        else {cssStr = '';}        \r",
                        "\r",
                        "        headerTplArr.push('<p class=\"touchtreegrid-header-cell ' + cssStr + \r",
                        "        (!Ext.isEmpty(data[j].initSortCls) ? ' '+data[j].initSortCls : '') + // see comments in handleColumnSort()\r",
                        "        '\" style=\"min-width:' + data[j].width +' !important;' +\r",
                        "        'max-width:'+data[j].width + ' !important; width:' + data[j].width + ' !important;' +\r",
                        "        styleStr + '\" dataIndex=\"'+data[j].dataIndex+'\">' + data[j].header + '</p>');               \r",
                        "    }\r",
                        "    headerTplArr.push('</div>');  \r",
                        "\r",
                        "    // Wrap with spacer to accomodate for disclosure icon(lines up columns better)\r",
                        "    var headerTplArr2 = [];\r",
                        "    if (disclose) {\r",
                        "        headerTplArr2.push('<div class=\"touchtreegrid-disclose-spacer\">');\r",
                        "        headerTplArr2 = headerTplArr2.concat(headerTplArr);\r",
                        "        headerTplArr2.push('</div>');  \r",
                        "    } else {\r",
                        "        headerTplArr2 = headerTplArr;\r",
                        "    }\r",
                        "\r",
                        "    headerTpl=headerTplArr2.join('');    \r",
                        "}\r",
                        "if (this.getIncludeHeader()) {\r",
                        "    header.setHtml(headerTpl);\r",
                        "}    \r",
                        "\r",
                        "\r",
                        "if (me.getApplyDefaultCollapseLevel() && !skipApplyDefaultCollapseLevel && !simpleList) {\r",
                        "    // custom implementations can request not to change collapse levels when refreshing\r",
                        "    me.doExpandDepth(me.getDefaultCollapseLevel());\r",
                        "}\r",
                        "\r",
                        "if (me.getIncludeFooter() && me.getIncludeFooterLevels() && !simpleList) {\r",
                        "    // Proceed to add expand/collapse levels  (horizontal scrolling toolbar LATER)\r",
                        "\r",
                        "    // First get total depth of treestore\r",
                        "    var store = list.getStore();\r",
                        "    maxDepth=0;\r",
                        "\r",
                        "    function doDrillDown(node) {\r",
                        "        if (!node.isLeaf()) {\r",
                        "            maxDepth = ((node.data.depth>maxDepth) ? node.data.depth : maxDepth);\r",
                        "\r",
                        "            node.childNodes.forEach(doDrillDown, me);\r",
                        "        }\r",
                        "    }\r",
                        "    store.each(doDrillDown, me);   \r",
                        "\r",
                        "    if (maxDepth>1) {\r",
                        "        // Remove button items 1+ if they exist\r",
                        "\r",
                        "        var btns = me.down('#touchtreegridbuttons');\r",
                        "        var itms = btns.getItems();\r",
                        "        var itmsOrigLength = itms.items.length;\r",
                        "        for (var k=itmsOrigLength-1; k>2; k--) {\r",
                        "            btns.remove(itms.items[k], true);\r",
                        "        }\r",
                        "\r",
                        "        var btnStyle = {};\r",
                        "\r",
                        "        // Add buton for each additional level\r",
                        "        var newbtn;\r",
                        "        for (var i=2; i <= maxDepth; i++) {\r",
                        "            if (colorDepth && colorDepthButtons) {\r",
                        "                btnStyle = {'background' : (!colorArr[i-1] ? 'white' : colorArr[i-1]),\r",
                        "                'color' : 'black'};\r",
                        "            }\r",
                        "            newbtn = {\r",
                        "                xtype: 'button',\r",
                        "                itemId: 'touchtreegriddepth'+i.toString(),\r",
                        "                cls  : 'touchtreegrid-expand-collapse-buttons',\r",
                        "                style : btnStyle,\r",
                        "                depth : i,\r",
                        "                text: i.toString(),\r",
                        "                listeners : {tap: function (button, e, options) {me.doExpandDepth(button.config.depth, button);}}\r",
                        "            };\r",
                        "\r",
                        "            btns.add(newbtn);\r",
                        "        }\r",
                        "\r",
                        "    }\r",
                        "}\r",
                        ""
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "formatNumbers",
                    "designer|params": [
                        "n",
                        "decPlaces",
                        "prefix",
                        "suffix",
                        "thouSeparator",
                        "decSeparator"
                    ],
                    "implHandler": [
                        "if (Ext.isEmpty(n)) {return n;};  // Don't format empty strings  ==\"\" || !n || isNaN(n)\r",
                        "decPlaces = (isNaN(decPlaces = Math.abs(decPlaces)) ? 2 : decPlaces);\r",
                        "prefix = (prefix == undefined ? \"\" : prefix);   // Example pass \"$\" sign for currency\r",
                        "suffix = (suffix == undefined ? \"\" : suffix);   // Example pass \"%\" sign for percents\r",
                        "\r",
                        "decSeparator = (decSeparator == undefined ? \".\" : decSeparator);\r",
                        "thouSeparator = (thouSeparator == undefined ? \",\" : thouSeparator);\r",
                        "sign = (n < 0 ? \"-\" : \"\");\r",
                        "i = parseInt(n = Math.abs(+n || 0).toFixed(decPlaces)) + \"\";\r",
                        "j = (((j = i.length) > 3) ? (j % 3) : 0);\r",
                        "return prefix + sign + (j ? i.substr(0, j) + thouSeparator : \"\") + \r",
                        "i.substr(j).replace(/(\\d{3})(?=\\d)/g, \"$1\" + thouSeparator) + \r",
                        "(decPlaces ? decSeparator + Math.abs(n - i).toFixed(decPlaces).slice(2) : \"\") + suffix;"
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "isObjectEmpty",
                    "designer|params": [
                        "myObj"
                    ],
                    "implHandler": [
                        "for(var key in myObj) {\r",
                        "    if (myObj.hasOwnProperty(key)) {\r",
                        "        return false;\r",
                        "    }\r",
                        "}\r",
                        "return true;"
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "handleColumnSort",
                    "designer|params": [
                        "e,t"
                    ],
                    "implHandler": [
                        "// Refer to updateHeader() for code to add tap listener on header toolbar\r",
                        "//  header.element.on('tap', me[\"handleColumnSort\"], me, {});\r",
                        "\r",
                        "var me        = this,\r",
                        "    list      = me.getList(),\r",
                        "    grouped   = list.getGrouped(),\r",
                        "    columns   = me.getColumns(),\r",
                        "    cNum      = columns.length,\r",
                        "    store     = list.getStore(),\r",
                        "    el        = Ext.get(t),\r",
                        "    headerEl  = me.down('#touchtreegridheader').element,\r",
                        "    dataIndex = el.getAttribute('dataIndex'),\r",
                        "    sorters   = store.getSorters(),\r",
                        "    asc       = 'x-grid-sort-asc',\r",
                        "    desc      = 'x-grid-sort-desc',\r",
                        "    myEvent   = me.getCustomColumnSortEvent(),\r",
                        "    columnsUpdated = false,\r",
                        "    c, colIndex, column, columnsUpd=[], colEl, sorter, dir,\r",
                        "    grouper, grouperSortProperty, grouperDirection, grouperProperty, mySortIdx, newDirCls;\r",
                        "\r",
                        "if (!dataIndex) return;  //Included in event of tap on extra toolbar space at far right\r",
                        "\r",
                        "for (c=0; c < cNum; c++) {\r",
                        "    column = columns[c];\r",
                        "    if (column.dataIndex === dataIndex) {break;}\r",
                        "}\r",
                        "colIndex = c;\r",
                        "\r",
                        "if (myEvent !== '') {\r",
                        "    // Custom event specified to be fired in lieu of default processing\r",
                        "    me.fireEvent(myEvent,{me: me, e: e, t: t,  el: el, headerEl: headerEl,\r",
                        "    dataIndex: dataIndex, column: column});\r",
                        "    return;    \r",
                        "}\r",
                        "\r",
                        "if (!column.sortable) return;\r",
                        "\r",
                        "grouper = store.getGrouper();\r",
                        "if (!Ext.isEmpty(grouper)) {\r",
                        "    grouperProperty = grouper.getProperty();\r",
                        "    grouperSortProperty = grouper.getSortProperty();\r",
                        "    grouperDirection = Ext.isEmpty(grouper.getDirection()) ? 'ASC' : grouper.getDirection();\r",
                        "}\r",
                        "\r",
                        "// sorters array may be prefilled with grouper-related sorts, last index is one for my current column sort\r",
                        "mySortIdx = sorters.length-1;\r",
                        "sorter    = sorters[mySortIdx];\r",
                        "dir       = sorter ? sorter.getDirection() : 'ASC';    \r",
                        "newDirCls = (dir === 'DESC' ? desc : asc);\r",
                        "\r",
                        "\r",
                        "// Sort items within grouper if defined\r",
                        "if (Ext.isEmpty(grouper)){\r",
                        "    store.sort([{property: dataIndex, direction: dir === 'DESC' ? 'ASC' : 'DESC'}]);    \r",
                        "} else {\r",
                        "    store.sort([{property: grouperSortProperty, direction: grouperDirection},\r",
                        "    {property: dataIndex, direction: dir === 'DESC' ? 'ASC' : 'DESC'}]);\r",
                        "}    \r",
                        "\r",
                        "// Copy columns[], update the copy then restore so that updateColumns() method isn't \r",
                        "// invoked via updateColumns() method until all updates are complete\r",
                        "columnsUpd = Ext.clone(columns); \r",
                        "\r",
                        "// Remove any prior sort indicators \r",
                        "for (c=0; c < cNum; c++) {\r",
                        "    colEl = Ext.get(headerEl.down('p.touchtreegrid-header-cell[dataIndex=' + columns[c].dataIndex + ']'));\r",
                        "    if (!me.isObjectEmpty(colEl)) {\r",
                        "        colEl.removeCls(asc);\r",
                        "        colEl.removeCls(desc);\r",
                        "    } \r",
                        "\r",
                        "\r",
                        "    // Process column shading if sorted properties are defined in columns[] array:\r",
                        "    // => headerStyleSorted, categStyleSorted, styleSorted\r",
                        "    if (c===colIndex) {\r",
                        "        // Save Original styles and update with sorted styles  (STYLE will override CSS if defined)\r",
                        "        if (!Ext.isEmpty(columnsUpd[c].headerCssSorted) && !Ext.isEmpty(columnsUpd[c].headerCss)) {\r",
                        "            if (Ext.isEmpty(columnsUpd[c].headerCssOrig)) {\r",
                        "                columnsUpd[c].headerCssOrig = columnsUpd[c].headerCss;\r",
                        "            }\r",
                        "            if (columnsUpd[c].headerCss !== columnsUpd[c].headerCssSorted) {\r",
                        "                columnsUpd[c].headerCss = columnsUpd[c].headerCssSorted;\r",
                        "                columnsUpd[c].initSortCls = newDirCls;   // Store new CLS to array so that doRefreshList() will render sort arrow correctly when redrawing         \r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }        \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].headerStyleSorted) && !Ext.isEmpty(columnsUpd[c].headerStyle)) {\r",
                        "            if (Ext.isEmpty(columnsUpd[c].headerStyleOrig)) {\r",
                        "                columnsUpd[c].headerStyleOrig = columnsUpd[c].headerStyle;\r",
                        "            }\r",
                        "            if (columnsUpd[c].headerStyle !== columnsUpd[c].headerStyleSorted) {\r",
                        "                columnsUpd[c].headerStyle = columnsUpd[c].headerStyleSorted;\r",
                        "                columnsUpd[c].initSortCls = newDirCls;   // Store new CLS to array so that doRefreshList() will render sort arrow correctly when redrawing         \r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }\r",
                        "\r",
                        "        \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].categCssSorted) && !Ext.isEmpty(columnsUpd[c].categCss)) {\r",
                        "            if (Ext.isEmpty(columnsUpd[c].categCssOrig)) {\r",
                        "                columnsUpd[c].categCssOrig = columnsUpd[c].categCss;\r",
                        "            }\r",
                        "            if (columnsUpd[c].categCss !== columnsUpd[c].categCssSorted) {\r",
                        "                columnsUpd[c].categCss = columnsUpd[c].categCssSorted;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        } \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].categStyleSorted) && !Ext.isEmpty(columnsUpd[c].categStyle)) {\r",
                        "            if (Ext.isEmpty(columnsUpd[c].categStyleOrig)) {\r",
                        "                columnsUpd[c].categStyleOrig = columnsUpd[c].categStyle;\r",
                        "            }\r",
                        "            if (columnsUpd[c].categStyle !== columnsUpd[c].categStyleSorted) {\r",
                        "                columnsUpd[c].categStyle = columnsUpd[c].categStyleSorted;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }       \r",
                        "\r",
                        "         \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].cssSorted) && !Ext.isEmpty(columnsUpd[c].css)) {\r",
                        "            if (Ext.isEmpty(columnsUpd[c].cssOrig)) {\r",
                        "                columnsUpd[c].cssOrig = columnsUpd[c].css;\r",
                        "            }\r",
                        "            if (columnsUpd[c].css !== columnsUpd[c].cssSorted) {\r",
                        "                columnsUpd[c].css = columnsUpd[c].cssSorted;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }\r",
                        "        if (!Ext.isEmpty(columnsUpd[c].styleSorted) && !Ext.isEmpty(columnsUpd[c].style)) {\r",
                        "            if (Ext.isEmpty(columnsUpd[c].styleOrig)) {\r",
                        "                columnsUpd[c].styleOrig = columnsUpd[c].style;\r",
                        "            }\r",
                        "            if (columnsUpd[c].style !== columnsUpd[c].styleSorted) {\r",
                        "                columnsUpd[c].style = columnsUpd[c].styleSorted;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }\r",
                        "\r",
                        "        \r",
                        "    } else {\r",
                        "        // Restore Original styles for non-sorted columnsUpd\r",
                        "        if (!Ext.isEmpty(columnsUpd[c].headerCssOrig) && !Ext.isEmpty(columnsUpd[c].headerCss)) {\r",
                        "            if (columnsUpd[c].headerCss !== columnsUpd[c].headerCssOrig) {\r",
                        "                columnsUpd[c].headerCss = columnsUpd[c].headerCssOrig;\r",
                        "                columnsUpd[c].initSortCls = '';      // reset                       \r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }        \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].headerStyleOrig) && !Ext.isEmpty(columnsUpd[c].headerStyle)) {\r",
                        "            if (columnsUpd[c].headerStyle !== columnsUpd[c].headerStyleOrig) {\r",
                        "                columnsUpd[c].headerStyle = columnsUpd[c].headerStyleOrig;\r",
                        "                columnsUpd[c].initSortCls = '';      // reset                       \r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }\r",
                        "        \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].categCssOrig) && !Ext.isEmpty(columnsUpd[c].categCss)) {\r",
                        "            if (columnsUpd[c].categCss !== columnsUpd[c].categCssOrig) {\r",
                        "                columnsUpd[c].categCss = columnsUpd[c].categCssOrig;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }   \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].categStyleOrig) && !Ext.isEmpty(columnsUpd[c].categStyle)) {\r",
                        "            if (columnsUpd[c].categStyle !== columnsUpd[c].categStyleOrig) {\r",
                        "                columnsUpd[c].categStyle = columnsUpd[c].categStyleOrig;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }   \r",
                        "             \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].cssOrig) && !Ext.isEmpty(columnsUpd[c].css)) {\r",
                        "            if (columnsUpd[c].css !== columnsUpd[c].cssOrig) {\r",
                        "                columnsUpd[c].css = columnsUpd[c].cssOrig;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }        \r",
                        "        if (!Ext.isEmpty(columnsUpd[c].styleOrig) && !Ext.isEmpty(columnsUpd[c].style)) {\r",
                        "            if (columnsUpd[c].style !== columnsUpd[c].styleOrig) {\r",
                        "                columnsUpd[c].style = columnsUpd[c].styleOrig;\r",
                        "                columnsUpdated = true;\r",
                        "            }                \r",
                        "        }        \r",
                        "    }\r",
                        "}\r",
                        "\r",
                        "if (columnsUpdated) {\r",
                        "    me.setColumns(columnsUpd);  \r",
                        "    me.doRefreshList();\r",
                        "}\r",
                        "else {list.refresh();}\r",
                        "\r",
                        "// Apply sort indicator to tapped column  (need this after doRefreshList() called .. but also handled in doRefreshList do to race conditioons)\r",
                        "var newEl = el.addCls(newDirCls);    \r",
                        "\r",
                        "\r",
                        "\r",
                        ""
                    ]
                }
            },
            {
                "type": "basicfunction",
                "reference": {
                    "name": "items",
                    "type": "array"
                },
                "codeClass": null,
                "userConfig": {
                    "fn": "updateFooter",
                    "designer|params": [
                        "footer"
                    ],
                    "implHandler": [
                        "if (this.getIncludeFooter() && !this.getSimpleList()) {\r",
                        "    this.insert(0, footer);\r",
                        "}"
                    ]
                }
            }
        ]
    },
    "linkedNodes": {},
    "boundStores": {},
    "boundModels": {}
}