/*
 * File: app/view/CensusDetailPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.CensusDetailPanel', {
    extend: 'Ext.Container',
    alias: 'widget.censusdetailpanel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label',
        'Ext.form.FieldSet',
        'Ext.field.Text'
    ],

    config: {
        cls: 'censusdetailpanel',
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                padding: '.4em 0 0 0',
                layout: {
                    type: 'hbox',
                    align: 'center'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'censusdetailbackbtn',
                        maxWidth: 80,
                        minWidth: 80,
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer',
                        width: 10
                    },
                    {
                        xtype: 'label',
                        itemId: 'censusdetaillabel',
                        maxWidth: '10em',
                        style: 'color : white'
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                minHeight: '1.5em',
                style: 'background: #5e6266; font-size: .8em;',
                items: [
                    {
                        xtype: 'label',
                        docked: 'left',
                        html: 'Number',
                        style: 'text-align: right; padding-right: 1em; padding-top: .1em;',
                        width: '66.666%'
                    },
                    {
                        xtype: 'label',
                        docked: 'right',
                        html: 'Percent',
                        style: 'padding-right: 1em; padding-top: .1em;'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                cls: 'censusfieldset1',
                height: '70em',
                itemId: 'censusscrollcont',
                maxHeight: '70em',
                minHeight: '70em',
                layout: 'hbox',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'container',
                        flex: 2,
                        cls: 'censusfieldset1',
                        height: '70em',
                        maxHeight: '70em',
                        minHeight: '70em',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                height: '70em',
                                itemId: 'censusfieldset1',
                                maxHeight: '70em',
                                minHeight: '70em',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        inputCls: 'detailtextfields',
                                        label: 'Field',
                                        labelWidth: '60%',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        flex: 1,
                        cls: 'censusfieldset2',
                        height: '70em',
                        maxHeight: '70em',
                        minHeight: '70em',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                height: '70em',
                                itemId: 'censusfieldset2',
                                maxHeight: '70em',
                                minHeight: '70em',
                                scrollable: false,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});