/*
 * File: app/view/griddetailpanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.griddetailpanel', {
    extend: 'Ext.Container',
    alias: 'widget.griddetailpanel',

    config: {
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                layout: {
                    align: 'center',
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        itemId: 'griddetailbackbtn',
                        maxWidth: 80,
                        minWidth: 80,
                        ui: 'back',
                        text: 'Back'
                    },
                    {
                        xtype: 'spacer',
                        width: 10
                    },
                    {
                        xtype: 'label',
                        html: '',
                        itemId: 'griddetaillabel',
                        style: 'color : white'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                flex: 1,
                itemId: 'griddetailfieldset',
                scrollable: 'vertical',
                items: [
                    {
                        xtype: 'textfield',
                        height: 78,
                        label: 'Field',
                        readOnly: true
                    }
                ]
            }
        ]
    }

});