/*
 * File: app/store/Task2.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.store.Task2', {
    extend: 'Ext.data.TreeStore',

    requires: [
        'TouchTreeGrid.model.Task'
    ],

    config: {
        autoLoad: true,
        model: 'TouchTreeGrid.model.Task',
        storeId: 'Task2',
        defaultRootProperty: 'items',
        root: {
            items: [
                {
                    text: 'Later this week',
                    expanded: true,
                    items: [
                        {
                            text: 'Call Mom',
                            comment: 'Sample comment',
                            check1: true,
                            option: 'second',
                            leaf: true
                        },
                        {
                            text: 'Later this week - Subjects',
                            items: [
                                {
                                    text: 'Calculus',
                                    leaf: true
                                },
                                {
                                    text: 'Physics',
                                    leaf: true
                                }
                            ]
                        }
                    ]
                },
                {
                    text: 'Today',
                    items: [
                        {
                            text: 'Mow Grass',
                            leaf: true
                        },
                        {
                            text: 'Buy Groceries',
                            leaf: true
                        },
                        {
                            text: 'Watch Game',
                            leaf: true
                        }
                    ]
                },
                {
                    text: 'Tomorrow',
                    items: [
                        {
                            text: 'Frisbee',
                            leaf: true
                        },
                        {
                            text: 'Cookout',
                            leaf: true
                        }
                    ]
                },
                {
                    text: 'On Hold',
                    items: [
                        {
                            text: 'Buy Clothes',
                            leaf: true
                        }
                    ]
                }
            ]
        }
    }
});