/*
 * File: app/view/TasksContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.TasksContainer', {
    extend: 'Ext.Container',
    alias: 'widget.tasksContainer',

    requires: [
        'TouchTreeGrid.view.TouchTreeGrid'
    ],

    config: {
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'tabpanel',
                itemId: 'tasksTabPanel',
                items: [
                    {
                        xtype: 'container',
                        title: 'Accordion',
                        itemId: 'accordioncont',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'touchtreegrid',
                                columns: [
                                    {
                                        dataIndex: 'text',
                                        width: '95%',
                                        style: ' text-align: left; font-size: 1.5em;',
                                        categStyle: 'font-weight: bold; font-size: 2em; padding-top: .2em; text-align: left; color: blue;',
                                        
                                    }
                                ],
                                listItemId: 'firstexamplelist',
                                includeFooterLevels: false,
                                helpHtml: './resources/html/TaskExample.html',
                                store: 'TaskAccordionStore',
                                includeHeader: false,
                                defaultCollapseLevel: 1,
                                singleExpand: true,
                                cls: [
                                    'x-touchtreegrid-list',
                                    'x-touchtreegrid-list-accordion'
                                ],
                                itemId: 'firstexample'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Tasks#2',
                        itemId: 'task2cont',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'touchtreegrid',
                                columns: [
                                    {
                                        dataIndex: 'text',
                                        width: '95%',
                                        style: ' text-align: left; font-size: 1.5em; padding-top: .2em;',
                                        categStyle: 'font-weight: bold; font-size: 2em; padding: .2em 0 0 .5em; text-align: left; color: blue;',
                                        
                                    }
                                ],
                                listItemId: 'task2grid',
                                includeFooter: false,
                                includeFooterLevels: false,
                                helpHtml: './resources/html/Tasks2Example.html',
                                store: 'task2Store',
                                disableSelection: false,
                                includeHeader: false,
                                arrowPctWidth: '0',
                                disableExpandCollapse: true,
                                cls: [
                                    'x-touchtreegrid-list',
                                    'x-touchtreegrid-list-task2'
                                ],
                                itemId: 'task2'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: 'Tasks#3',
                        itemId: 'task3cont',
                        layout: {
                            type: 'fit'
                        },
                        items: [
                            {
                                xtype: 'touchtreegrid',
                                columns: [
                                    {
                                        dataIndex: 'text',
                                        width: '95%',
                                        style: ' text-align: left; font-size: 1.5em; padding-top: .2em;',
                                        categStyle: 'font-weight: bold; font-size: 2em; padding: .2em 0 0 .5em; text-align: left; color: blue;',
                                        
                                    }
                                ],
                                listItemId: 'task3grid',
                                includeFooter: false,
                                includeFooterLevels: false,
                                helpHtml: './resources/html/Tasks3Example.html',
                                store: 'task3Store',
                                disableSelection: false,
                                includeHeader: false,
                                arrowPctWidth: '0',
                                disableExpandCollapse: true,
                                cls: [
                                    'x-touchtreegrid-list',
                                    'x-touchtreegrid-list-task3'
                                ],
                                itemId: 'task3'
                            }
                        ]
                    }
                ],
                tabBar: {
                    cls: 'projectTabBar',
                    docked: 'top',
                    style: 'background-image: -webkit-linear-gradient(top, rgb(86, 167, 223), rgb(43, 145, 215) 3%, rgb(33, 117, 175));',
                    ui: 'light'
                }
            }
        ]
    }

});