/*
 * File: app/view/AccordionCont.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.AccordionCont', {
    extend: 'Ext.Container',
    alias: 'widget.accordionCont',

    config: {
        itemId: 'accordionCont',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'touchtreegrid',
                store: 'TaskAccordionStore',
                columns: [
                    {
                        dataIndex: 'text',
                        width: '95%',
                        style: ' text-align: left; font-size: 1.5em;',
                        categStyle: 'font-weight: bold; font-size: 2em; padding-top: .2em; text-align: left; color: blue;',
                        
                    }
                ],
                listItemId: 'firstexamplelist',
                includeFooterLevels: false,
                includeHeader: false,
                defaultCollapseLevel: 1,
                helpHtml: './resources/html/TaskExample.html',
                singleExpand: true,
                cls: [
                    'x-touchtreegrid-list',
                    'x-touchtreegrid-list-accordion'
                ],
                itemId: 'firstexample'
            }
        ]
    }

});