/*
 * File: app/view/CensusMaineContainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.CensusMaineContainer', {
    extend: 'Ext.Container',
    alias: 'widget.censusMaineContainer',

    config: {
        itemId: 'censusMaineContainer',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'touchtreegrid',
                store: 'censusmaine2000store',
                onItemDisclosure: true,
                listItemId: 'censusmainelist',
                categIndentPct: '2',
                categDepthColors: true,
                renderers: {
                    renderer_displayIn1000s: function(value)
                 {return this.formatNumbers(Math.round(Number(value)/1000), 0);}
                },
                defaultCollapseLevel: 2,
                helpHtml: './resources/html/CensusExample.html',
                arrowPctWidth: '4',
                cls: [
                    'x-touchtreegrid-list',
                    'x-touchtreegrid-list-censusmaine'
                ],
                itemId: 'censusmaine'
            }
        ]
    },

    initialize: function() {
        this.callParent();
        if (!Ext.os.is.Phone) {  // 2% arrow width for tablets, 4% (default) for phones
            this.down('#censusmaine').setArrowPctWidth('2');
        }
    }

});