/*
 * File: app/view/Example2Bcontainer.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.view.Example2Bcontainer', {
    extend: 'Ext.Container',
    alias: 'widget.example2Bcontainer',

    config: {
        itemId: 'example2Bcontainer',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'touchtreegrid',
                store: 'projectsStore',
                onItemDisclosure: true,
                columns: [
                    {
                        header: 'Task',
                        dataIndex: 'task',
                        width: '35%',
                        style: 'text-align: left;',
                        categStyle: 'font-weight: bold; text-align: left; color: #f4f4f4;',
                        headerStyle: 'text-align: left; color: #ccc;'
                    },
                    {
                        header: 'User',
                        dataIndex: 'user',
                        width: '35%',
                        style: 'text-align: left; padding-left: .5em;',
                        categStyle: 'text-align: left;padding-left: .5em;',
                        headerStyle: 'text-align: left; color: #ccc;padding-left: .5em;'
                    },
                    {
                        header: 'Dur',
                        dataIndex: 'duration',
                        width: '15%',
                        style: 'text-align: right;',
                        categStyle: 'text-align: right;',
                        headerStyle: 'text-align: right; color: #ccc;'
                    }/*,
                    {
                        header: 'Done?',
                        dataIndex: 'done',
                        width: '15%',
                        style: 'text-align: right; font-size: .6em;',
                        categStyle: 'text-align: right;font-size: .6em;',
                        headerStyle: 'text-align: right; color: #ccc;'
                    }*/
                ],
                variableHeights: false,
                itemHeight: 32,
                listItemId: 'example2Blist',
                includeFooter: true,
                includeFooterLevels: true,
                categDepthColors: true,
                categDepthColorsArr: [
                    '#808127',
                    '#949569',
                    '#C5C678'
                ],
                categDepthColorButtons: true,
                includeHeader: true,
                applyDefaultCollapseLevel: false,
                helpHtml: './resources/html/Project2Example.html',
                categCssArr: [
                    'touchtreegrid-list-categ0',
                    'touchtreegrid-list-categ',
                    'touchtreegrid-list-categ'
                ],
                cls: [
                    'x-touchtreegrid-list',
                    'x-touchtreegrid-list-example2',
                    'x-touchtreegrid-list-example2B'
                ],
                itemId: 'example2B'
            }
        ]
    }

});