/*
 * File: app/model/Census.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.model.Census', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'CATEG',
                type: 'string'
            },
            {
                name: 'ID'
            },
            {
                name: 'PARENT_ID'
            },
            {
                name: 'TotalPopulation',
                type: 'int'
            },
            {
                name: 'Male',
                type: 'int'
            },
            {
                name: 'Female',
                type: 'int'
            },
            {
                name: 'Under5years',
                type: 'int'
            },
            {
                name: 'Age5to9',
                type: 'int'
            },
            {
                name: 'Age10to14',
                type: 'int'
            },
            {
                name: 'Age15to19',
                type: 'int'
            },
            {
                name: 'Age20to24',
                type: 'int'
            },
            {
                name: 'Age25to34',
                type: 'int'
            },
            {
                name: 'Age35to44',
                type: 'int'
            },
            {
                name: 'Age45to54',
                type: 'int'
            },
            {
                name: 'Age55to59',
                type: 'int'
            },
            {
                name: 'Age60to64',
                type: 'int'
            },
            {
                name: 'Age65to74',
                type: 'int'
            },
            {
                name: 'Age75to84',
                type: 'int'
            },
            {
                name: 'Age85andOver',
                type: 'int'
            },
            {
                name: 'MedianAge',
                type: 'int'
            },
            {
                name: 'Age18andOver',
                type: 'int'
            },
            {
                name: 'Age18andOverMale',
                type: 'int'
            },
            {
                name: 'Age18andOverFemale',
                type: 'int'
            },
            {
                name: 'Age21andOver',
                type: 'int'
            },
            {
                name: 'Age62andOver',
                type: 'int'
            },
            {
                name: 'Age65andOver',
                type: 'int'
            },
            {
                name: 'Age65andOverMale',
                type: 'int'
            },
            {
                name: 'Age65andOverFemale',
                type: 'int'
            }
        ]
    }
});