/*
 * File: app/model/Projects.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TouchTreeGrid.model.Projects', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'task',
                type: 'string'
            },
            {
                name: 'user',
                type: 'string'
            },
            {
                name: 'duration',
                type: 'float'
            },
            {
                name: 'done',
                type: 'boolean'
            }
        ]
    }
});